# Copyright (c) 2023-2024 Rivos, Inc.
# SPDX-License-Identifier: Apache2

"""OTP descriptors.

   :author: Emmanuel Blot <eblot@rivosinc.com>
"""

from logging import getLogger
from typing import NamedTuple, Optional, TYPE_CHECKING, TextIO

from ot.top import OpenTitanTop
from ot.util.misc import redent
from .partition import OtpPartition

if TYPE_CHECKING:
    from .map import OtpMap


class OtpSlotDescriptor(NamedTuple):
    """A location descriptor in OTP, either a whole partition or an item.

       It has no other purpose than storing intermediate info as a container.
    """

    name: str
    """Name of the slot."""

    offset: str
    """Offset in bytes."""

    size: str
    """Size in bytes."""

    gen: bool = False
    """Whether this slot is generated by the script or defined."""

    part: bool = False
    """Whether the slot defines the whole partition or a single item."""


class OtpPartitionDesc:
    """OTP Partition descriptor generator."""

    ATTRS = {
        'size': None,
        'offset': None,
        'digest_offset': None,
        'zer_offset': None,
        'hw_digest': '',
        'sw_digest': '',
        'secret': '',
        'variant': 'buffer',
        'write_lock': 'wlock',
        'read_lock': 'rlock',
        'integrity': '',
        'zeroizable': '',
        'iskeymgr': '',
        'iskeymgr_creator': '',
        'iskeymgr_owner': '',
        'wide': ''
    }

    def __init__(self, otpmap: 'OtpMap'):
        self._log = getLogger('otp.partdesc')
        self._otpmap = otpmap

    def save(self, kind: str, hjname: str, scriptname: str, cfp: TextIO) \
            -> None:
        """Generate a source file with a static description for the partitions.

           :param kind: kind of generation output
           :param hjname: the name of the input HJSON configuration file
           :param scriptname: the name of the script that generates this output
           :param cfp: the output text stream
        """
        # pylint: disable=f-string-without-interpolation
        if kind != 'qemu':
            raise NotImplementedError(f'No support for {kind}')
        attrs = {n: getattr(self, f'_convert_to_{k}') if k else lambda x: x
                 for n, k in self.ATTRS.items() if k is not None}
        msg = f'Generated from {hjname} with {scriptname}'
        git_version = self._otpmap.git_version
        if git_version:
            print(f'/*\n * {msg}\n * Top version: {git_version}\n */', file=cfp)
        else:
            print(f'/* ${msg} */', file=cfp)
        print(file=cfp)
        print('/* clang-format off */', file=cfp)
        print('/* NOLINTBEGIN */', file=cfp)
        print('static const OtOTPPartDesc OtOTPPartDescs[] = {', file=cfp)
        for part in self._otpmap.enumerate_partitions():
            print(f'    [OTP_PART_{part.name}] = {{', file=cfp)
            print(f'        .size = {part.size}u,', file=cfp)
            print(f'        .offset = {part.offset}u,', file=cfp)
            if part.zer_offset is not None:
                print(f'        .zer_offset = {part.zer_offset}u,',
                      file=cfp)
            else:
                print(f'        .zer_offset = UINT16_MAX,',   # noqa: F541
                      file=cfp)
            if part.digest_offset is not None:
                print(f'        .digest_offset = {part.digest_offset}u,',
                      file=cfp)
            else:
                print(f'        .digest_offset = UINT16_MAX,',   # noqa: F541
                      file=cfp)
            for attr in attrs:
                value = getattr(part, attr, None)
                if value is None:
                    continue
                convs = attrs[attr](value)
                if not isinstance(convs, list):
                    convs = [convs]
                for conv in convs:
                    if isinstance(conv, tuple):
                        attr_name = conv[0]
                        attr_val = conv[1]
                    else:
                        attr_name = attr
                        attr_val = conv
                    if isinstance(attr_val, bool):
                        attr_val = str(attr_val).lower()
                    print(f'        .{attr_name} = {attr_val},', file=cfp)
            print(f'    }},', file=cfp)  # noqa: F541
        print('};', file=cfp)
        print('', file=cfp)
        print('#define OTP_PART_COUNT ARRAY_SIZE(OtOTPPartDescs)', file=cfp)
        print(file=cfp)
        print('/* NOLINTEND */', file=cfp)
        print('/* clang-format on */', file=cfp)
        # pylint: enable=f-string-without-interpolation

    @classmethod
    def _convert_to_bool(cls, value) -> str:
        return str(value).lower()

    @classmethod
    def _convert_to_buffer(cls, value) -> tuple[str, bool]:
        return {
            'unbuffered': ('buffered', False),
            'buffered': ('buffered', True),
            'lifecycle': ('buffered', True),
        }[value.lower()]

    @classmethod
    def _convert_to_wlock(cls, value) -> bool:
        return value == 'digest'

    @classmethod
    def _convert_to_rlock(cls, value) -> list[tuple[str, bool]]:
        value = value.lower()
        if value == 'csr':
            return [('read_lock_csr', True), ('read_lock', True)]
        if value == 'digest':
            return 'read_lock', True
        if value == 'none':
            return 'read_lock', False
        assert False, 'Unknown RLOCK type'


class OtpRegisterDef:
    """OTP Partition register generator."""

    def __init__(self, otpmap: 'OtpMap'):
        self._log = getLogger('otp.reg')
        self._otpmap = otpmap

    def save(self, kind: str, topname: Optional[str], hjname: str,
             scriptname: str, cfp: TextIO) -> None:
        """Generate a source file with register definition for the partitions.

           :param kind: kind of generation output
           :param topname: the name of the OpenTitan top
           :param hjname: the name of the input HJSON configuration file
           :param scriptname: the name of the script that generates this output
           :param cfp: the output text stream
        """
        try:
            save = getattr(self, f'_save_{kind.lower()}')
        except AttributeError as exc:
            raise NotImplementedError(f'No support for {kind}') from exc
        slots: list[OtpSlotDescriptor] = []
        for part in self._otpmap.enumerate_partitions():
            offset = part.offset
            slots.append(OtpSlotDescriptor(part.name, offset, part.size, True,
                                           True))
            for itname, itdict in part.items.items():
                size = itdict['size']
                if not itname.startswith(f'{part.name}_'):
                    name = f'{part.name}_{itname}'.upper()
                else:
                    name = itname
                slots.append(OtpSlotDescriptor(name, offset, size))
                offset += size
            zeroizable = getattr(part, 'zeroizable', False)
            digest = any(getattr(part, f'{k}w_digest', False) for k in 'sh')
            if digest:
                offset = part.offset + part.size - OtpPartition.DIGEST_SIZE
                if zeroizable:
                    offset -= OtpPartition.ZER_SIZE
                slots.append(OtpSlotDescriptor(f'{part.name}_DIGEST', offset,
                                               OtpPartition.DIGEST_SIZE, True))
            if zeroizable:
                offset = part.offset + part.size -  OtpPartition.DIGEST_SIZE
                slots.append(OtpSlotDescriptor(f'{part.name}_ZER', offset,
                                               OtpPartition.ZER_SIZE, True))

        save(topname, hjname, scriptname, cfp, slots)

    def _save_qemu(self, topname: Optional[str], hjname: str, scriptname: str,
                   cfp: TextIO, slots: list[OtpSlotDescriptor]) -> None:
        msg = f'Generated from {hjname} with {scriptname}'
        git_version = self._otpmap.git_version
        if git_version:
            print(f'/*\n * {msg}\n * Top version: {git_version}\n */', file=cfp)
        else:
            print(f'/* ${msg} */', file=cfp)
        print(file=cfp)
        for slot in slots:
            if slot.part:
                continue
            print(f'REG32({slot.name}, {slot.offset}u)', file=cfp)
        print(file=cfp)

        regwidth = max(len(s.name) for s in slots)
        regwidth += len('_SIZE')
        for slot in slots:
            if slot.gen and not slot.part:
                continue
            name = f'{slot.name}_SIZE'
            print(f'#define {name:{regwidth}s} {slot.size}u', file=cfp)
        print(file=cfp)

        part_names = [slot.name for slot in slots if slot.part]
        pcount = len(part_names)
        part_names = [f'OTP_PART_{pn}' for pn in part_names]
        part_names.extend((
            'OTP_PART_COUNT',
            'OTP_ENTRY_DAI = OTP_PART_COUNT, '
                '/* Fake partitions for error (...) */',
            'OTP_ENTRY_KDI, /* Key derivation issue, not really OTP */',
            'OTP_ENTRY_COUNT'))
        print('typedef enum {', file=cfp)
        for pname in part_names:
            print(f'    {pname}{"," if "," not in pname else ""}', file=cfp)
        print('} OtOTPPartitionType;', file=cfp)
        print(file=cfp)

        print('static const char *PART_NAMES[] = {', file=cfp)
        print('    /* clang-format off */', file=cfp)
        for pname in part_names[:pcount]:
            print(f'    OTP_NAME_ENTRY({pname}),', file=cfp)
        print('    /* fake partitions */', file=cfp)
        print('    OTP_NAME_ENTRY(OTP_ENTRY_DAI),', file=cfp)
        print('    OTP_NAME_ENTRY(OTP_ENTRY_KDI),', file=cfp)
        print('    /* clang-format on */', file=cfp)
        print('};', file=cfp)
        print(file=cfp)

        cases: list[str] = []
        for slot in slots:
            if slot.part:
                continue
            if slot.gen:
                cases.append(f'CASE_WIDE({slot.name});')
            elif slot.size > 4:
                cases.append(f'CASE_RANGE({slot.name});')
            elif slot.size == 1:
                cases.append(f'CASE_BYTE({slot.name});')
            elif slot.size < 4:
                cases.append(f'CASE_SUB({slot.name}, {slot.size}u);')
            else:
                cases.append(f'CASE_REG({slot.name});')

        code = '''
        static const char *ot_otp_swcfg_reg_name(unsigned swreg)
        {
        #define CASE_BYTE(_reg_) \\
            case A_##_reg_: \\
                return stringify(_reg_)
        #define CASE_SUB(_reg_, _sz_) \\
            case A_##_reg_...(A_##_reg_ + (_sz_)): \\
                return stringify(_reg_)
        #define CASE_REG(_reg_) \\
            case A_##_reg_...(A_##_reg_ + 3u): \\
                return stringify(_reg_)
        #define CASE_WIDE(_reg_) \\
            case A_##_reg_...(A_##_reg_ + 7u): \\
                return stringify(_reg_)
        #define CASE_RANGE(_reg_) \\
            case A_##_reg_...(A_##_reg_ + (_reg_##_SIZE) - 1u): \\
                return stringify(_reg_)

            switch (swreg) {
                _CASES_
            default:
                return "<?>";
            }

        #undef CASE_BYTE
        #undef CASE_SUB
        #undef CASE_REG
        #undef CASE_RANGE
        #undef CASE_DIGEST
        }
        '''
        if topname:
            tname = OpenTitanTop.short_name(topname)
            if tname:
                code = code.replace('ot_otp_swcfg_reg_name',
                                    f'ot_otp_{tname}_swcfg_reg_name')
        code = redent(code)
        code = code.replace('_CASES_', '\n        '.join(cases))
        print(redent(code), '', file=cfp)

    def _save_bmtest(self, topname: Optional[str], hjname: str, scriptname: str,
                     cfp: TextIO, slots: list[OtpSlotDescriptor]) -> None:
        # pylint: disable=unused-argument
        print(f'// Generated from {hjname} with {scriptname}', file=cfp)
        if self._otpmap.git_version:
            print(f'// Top version: {self._otpmap.git_version}', file=cfp)
        print(file=cfp)
        rec_p2 = 1 << (len(slots) - 1).bit_length()
        print(f'#![recursion_limit = "{rec_p2}"]', file=cfp)
        print(file=cfp)
        print('#[derive(Clone, Copy, Debug, PartialEq)]', file=cfp)
        print('pub enum Partition {', file=cfp)
        part_names = [slot.name for slot in slots if slot.part]
        for pname in part_names:
            pname = pname.title().replace('_', '')
            print(f'    {pname},', file=cfp)
        print('}', file=cfp)
        print(file=cfp)
        print('register_structs! {', file=cfp)
        print('    pub OtpSwCfgRegs {', file=cfp)
        slot = OtpSlotDescriptor('', 0, 0)  # default slot if none is defined
        end = 0
        rsv = 0
        for slot in slots:
            if slot.part:
                continue
            if slot.offset > end:
                missing = slot.offset - end
                count = missing // 4
                if count > 1:
                    print(f'        (0x{end:04x} => '
                          f'_reserved{rsv}: [ReadOnly<u32>; {count}]),',
                          file=cfp)
                else:
                    width = missing * 8
                    print(f'        (0x{end:04x} => '
                          f'_reserved{rsv}: ReadOnly<u{width}>),', file=cfp)
                rsv += 1
            if slot.size <= 4:
                width = slot.size * 8
                print(f'        (0x{slot.offset:04x} => '
                      f'{slot.name.lower()}: ReadOnly<u{width}>),', file=cfp)
            else:
                count = slot.size // 4
                print(f'        (0x{slot.offset:04x} => '
                      f'{slot.name.lower()}: [ReadOnly<u32>; {count}]),',
                      file=cfp)
            end = slot.offset + slot.size
        print(f'        (0x{slot.offset+slot.size:04x} => @END),', file=cfp)
        print('    }', file=cfp)
        print('}', file=cfp)
        print(file=cfp)
