/*
 * QEMU OpenTitan Darjeeling One Time Programmable (OTP) implementation
 *
 * Copyright (c) 2023-2025 Rivos, Inc.
 * Copyright (c) 2025 lowRISC contributors.
 *
 * Author(s):
 *  Emmanuel Blot <eblot@rivosinc.com>
 *  Loïc Lefort <loic@rivosinc.com>
 *  Alex Jones <alex.jones@lowrisc.org>
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 *
 * Based on OpenTitan 5fe6fe8605
 */

#include "qemu/osdep.h"
#include "qemu/log.h"
#include "qom/object.h"
#include "hw/opentitan/ot_otp_dj.h"
#include "hw/opentitan/ot_otp_engine.h"
#include "hw/opentitan/ot_otp_impl_if.h"
#include "trace.h"

#define NUM_ERROR_ENTRIES       24u
#define NUM_PART                22u
#define NUM_PART_BUF            7u
#define NUM_PART_UNBUF          15u
#define NUM_SRAM_KEY_REQ_SLOTS  4u
#define NUM_SW_CFG_WINDOW_WORDS 4096u

#define OTP_BYTE_ADDR_WIDTH 14u

/* clang-format off */
/* Core registers */
REG32(STATUS, 0x010u)
    FIELD(STATUS, VENDOR_TEST_ERROR, 0u, 1u)
    FIELD(STATUS, CREATOR_SW_CFG_ERROR, 1u, 1u)
    FIELD(STATUS, OWNER_SW_CFG_ERROR, 2u, 1u)
    FIELD(STATUS, OWNERSHIP_SLOT_STATE_ERROR, 3u, 1u)
    FIELD(STATUS, ROT_CREATOR_AUTH_ERROR, 4u, 1u)
    FIELD(STATUS, ROT_OWNER_AUTH_SLOT0_ERROR, 5u, 1u)
    FIELD(STATUS, ROT_OWNER_AUTH_SLOT1_ERROR, 6u, 1u)
    FIELD(STATUS, PLAT_INTEG_AUTH_SLOT0_ERROR, 7u, 1u)
    FIELD(STATUS, PLAT_INTEG_AUTH_SLOT1_ERROR, 8u, 1u)
    FIELD(STATUS, PLAT_OWNER_AUTH_SLOT0_ERROR, 9u, 1u)
    FIELD(STATUS, PLAT_OWNER_AUTH_SLOT1_ERROR, 10u, 1u)
    FIELD(STATUS, PLAT_OWNER_AUTH_SLOT2_ERROR, 11u, 1u)
    FIELD(STATUS, PLAT_OWNER_AUTH_SLOT3_ERROR, 12u, 1u)
    FIELD(STATUS, EXT_NVM_ERROR, 13u, 1u)
    FIELD(STATUS, ROM_PATCH_ERROR, 14u, 1u)
    FIELD(STATUS, HW_CFG0_ERROR, 15u, 1u)
    FIELD(STATUS, HW_CFG1_ERROR, 16u, 1u)
    FIELD(STATUS, SECRET0_ERROR, 17u, 1u)
    FIELD(STATUS, SECRET1_ERROR, 18u, 1u)
    FIELD(STATUS, SECRET2_ERROR, 19u, 1u)
    FIELD(STATUS, SECRET3_ERROR, 20u, 1u)
    FIELD(STATUS, LIFE_CYCLE_ERROR, 21u, 1u)
    FIELD(STATUS, DAI_ERROR, 22u, 1u)
    FIELD(STATUS, LCI_ERROR, 23u, 1u)
    FIELD(STATUS, TIMEOUT_ERROR, 24u, 1u)
    FIELD(STATUS, LFSR_FSM_ERROR, 25u, 1u)
    FIELD(STATUS, SCRAMBLING_FSM_ERROR, 26u, 1u)
    FIELD(STATUS, KEY_DERIV_FSM_ERROR, 27u, 1u)
    FIELD(STATUS, BUS_INTEG_ERROR, 28u, 1u)
    FIELD(STATUS, DAI_IDLE, 29u, 1u)
    FIELD(STATUS, CHECK_PENDING, 30u, 1u)
REG32(ERR_CODE_0, 0x014u)
REG32(ERR_CODE_1, 0x018u)
REG32(ERR_CODE_2, 0x01cu)
REG32(ERR_CODE_3, 0x020u)
REG32(ERR_CODE_4, 0x024u)
REG32(ERR_CODE_5, 0x028u)
REG32(ERR_CODE_6, 0x02cu)
REG32(ERR_CODE_7, 0x030u)
REG32(ERR_CODE_8, 0x034u)
REG32(ERR_CODE_9, 0x038u)
REG32(ERR_CODE_10, 0x03cu)
REG32(ERR_CODE_11, 0x040u)
REG32(ERR_CODE_12, 0x044u)
REG32(ERR_CODE_13, 0x048u)
REG32(ERR_CODE_14, 0x04cu)
REG32(ERR_CODE_15, 0x050u)
REG32(ERR_CODE_16, 0x054u)
REG32(ERR_CODE_17, 0x058u)
REG32(ERR_CODE_18, 0x05cu)
REG32(ERR_CODE_19, 0x060u)
REG32(ERR_CODE_20, 0x064u)
REG32(ERR_CODE_21, 0x068u)
REG32(ERR_CODE_22, 0x06cu)
REG32(ERR_CODE_23, 0x070u)
REG32(DIRECT_ACCESS_REGWEN, 0x074u)
    FIELD(DIRECT_ACCESS_REGWEN, REGWEN, 0u, 1u)
REG32(DIRECT_ACCESS_CMD, 0x078u)
REG32(DIRECT_ACCESS_ADDRESS, 0x07cu)
    FIELD(DIRECT_ACCESS_ADDRESS, ADDRESS, 0u, 14u)
REG32(DIRECT_ACCESS_WDATA_0, 0x080u)
REG32(DIRECT_ACCESS_WDATA_1, 0x084u)
REG32(DIRECT_ACCESS_RDATA_0, 0x088u)
REG32(DIRECT_ACCESS_RDATA_1, 0x08cu)
REG32(CHECK_TRIGGER_REGWEN, 0x090u)
    FIELD(CHECK_TRIGGER_REGWEN, REGWEN, 0u, 1u)
REG32(CHECK_TRIGGER, 0x094u)
    FIELD(CHECK_TRIGGER, INTEGRITY, 0u, 1u)
    FIELD(CHECK_TRIGGER, CONSISTENCY, 1u, 1u)
REG32(CHECK_REGWEN, 0x098u)
    FIELD(CHECK_REGWEN, REGWEN, 0u, 1u)
REG32(CHECK_TIMEOUT, 0x09cu)
REG32(INTEGRITY_CHECK_PERIOD, 0x0a0u)
REG32(CONSISTENCY_CHECK_PERIOD, 0x0a4u)
REG32(VENDOR_TEST_READ_LOCK, 0x0a8u)
REG32(CREATOR_SW_CFG_READ_LOCK, 0x0acu)
REG32(OWNER_SW_CFG_READ_LOCK, 0x0b0u)
REG32(OWNERSHIP_SLOT_STATE_READ_LOCK, 0x0b4u)
REG32(ROT_CREATOR_AUTH_READ_LOCK, 0x0b8u)
REG32(ROT_OWNER_AUTH_SLOT0_READ_LOCK, 0x0bcu)
REG32(ROT_OWNER_AUTH_SLOT1_READ_LOCK, 0x0c0u)
REG32(PLAT_INTEG_AUTH_SLOT0_READ_LOCK, 0x0c4u)
REG32(PLAT_INTEG_AUTH_SLOT1_READ_LOCK, 0x0c8u)
REG32(PLAT_OWNER_AUTH_SLOT0_READ_LOCK, 0x0ccu)
REG32(PLAT_OWNER_AUTH_SLOT1_READ_LOCK, 0x0d0u)
REG32(PLAT_OWNER_AUTH_SLOT2_READ_LOCK, 0x0d4u)
REG32(PLAT_OWNER_AUTH_SLOT3_READ_LOCK, 0x0d8u)
REG32(EXT_NVM_READ_LOCK, 0x0dcu)
REG32(ROM_PATCH_READ_LOCK, 0x0e0u)
REG32(VENDOR_TEST_DIGEST_0, 0x0e4u)
REG32(VENDOR_TEST_DIGEST_1, 0x0e8u)
REG32(CREATOR_SW_CFG_DIGEST_0, 0x0ecu)
REG32(CREATOR_SW_CFG_DIGEST_1, 0x0f0u)
REG32(OWNER_SW_CFG_DIGEST_0, 0x0f4u)
REG32(OWNER_SW_CFG_DIGEST_1, 0x0f8u)
REG32(ROT_CREATOR_AUTH_DIGEST_0, 0x0fcu)
REG32(ROT_CREATOR_AUTH_DIGEST_1, 0x100u)
REG32(ROT_OWNER_AUTH_SLOT0_DIGEST_0, 0x104u)
REG32(ROT_OWNER_AUTH_SLOT0_DIGEST_1, 0x108u)
REG32(ROT_OWNER_AUTH_SLOT1_DIGEST_0, 0x10cu)
REG32(ROT_OWNER_AUTH_SLOT1_DIGEST_1, 0x110u)
REG32(PLAT_INTEG_AUTH_SLOT0_DIGEST_0, 0x114u)
REG32(PLAT_INTEG_AUTH_SLOT0_DIGEST_1, 0x118u)
REG32(PLAT_INTEG_AUTH_SLOT1_DIGEST_0, 0x11cu)
REG32(PLAT_INTEG_AUTH_SLOT1_DIGEST_1, 0x120u)
REG32(PLAT_OWNER_AUTH_SLOT0_DIGEST_0, 0x124u)
REG32(PLAT_OWNER_AUTH_SLOT0_DIGEST_1, 0x128u)
REG32(PLAT_OWNER_AUTH_SLOT1_DIGEST_0, 0x12cu)
REG32(PLAT_OWNER_AUTH_SLOT1_DIGEST_1, 0x130u)
REG32(PLAT_OWNER_AUTH_SLOT2_DIGEST_0, 0x134u)
REG32(PLAT_OWNER_AUTH_SLOT2_DIGEST_1, 0x138u)
REG32(PLAT_OWNER_AUTH_SLOT3_DIGEST_0, 0x13cu)
REG32(PLAT_OWNER_AUTH_SLOT3_DIGEST_1, 0x140u)
REG32(ROM_PATCH_DIGEST_0, 0x144u)
REG32(ROM_PATCH_DIGEST_1, 0x148u)
REG32(HW_CFG0_DIGEST_0, 0x14cu)
REG32(HW_CFG0_DIGEST_1, 0x150u)
REG32(HW_CFG1_DIGEST_0, 0x154u)
REG32(HW_CFG1_DIGEST_1, 0x158u)
REG32(SECRET0_DIGEST_0, 0x15cu)
REG32(SECRET0_DIGEST_1, 0x160u)
REG32(SECRET1_DIGEST_0, 0x164u)
REG32(SECRET1_DIGEST_1, 0x168u)
REG32(SECRET2_DIGEST_0, 0x16cu)
REG32(SECRET2_DIGEST_1, 0x170u)
REG32(SECRET3_DIGEST_0, 0x174u)
REG32(SECRET3_DIGEST_1, 0x178u)

/* Software Config Window registers (at offset SW_CFG_WINDOW_OFFSET) */
REG32(VENDOR_TEST_SCRATCH, 0u)
REG32(VENDOR_TEST_DIGEST, 56u)
REG32(CREATOR_SW_CFG_AST_CFG, 64u)
REG32(CREATOR_SW_CFG_AST_INIT_EN, 188u)
REG32(CREATOR_SW_CFG_OVERRIDES, 192u)
REG32(CREATOR_SW_CFG_ROM_EXT_SKU, 224u)
REG32(CREATOR_SW_CFG_SIGVERIFY_RSA_MOD_EXP_IBEX_EN, 228u)
REG32(CREATOR_SW_CFG_SIGVERIFY_RSA_KEY_EN, 232u)
REG32(CREATOR_SW_CFG_SIGVERIFY_SPX_EN, 240u)
REG32(CREATOR_SW_CFG_SIGVERIFY_SPX_KEY_EN, 244u)
REG32(CREATOR_SW_CFG_FLASH_DATA_DEFAULT_CFG, 252u)
REG32(CREATOR_SW_CFG_FLASH_INFO_BOOT_DATA_CFG, 256u)
REG32(CREATOR_SW_CFG_FLASH_HW_INFO_CFG_OVERRIDE, 260u)
REG32(CREATOR_SW_CFG_RNG_EN, 264u)
REG32(CREATOR_SW_CFG_JITTER_EN, 268u)
REG32(CREATOR_SW_CFG_RET_RAM_RESET_MASK, 272u)
REG32(CREATOR_SW_CFG_MANUF_STATE, 276u)
REG32(CREATOR_SW_CFG_ROM_EXEC_EN, 280u)
REG32(CREATOR_SW_CFG_CPUCTRL, 284u)
REG32(CREATOR_SW_CFG_MIN_SEC_VER_ROM_EXT, 288u)
REG32(CREATOR_SW_CFG_MIN_SEC_VER_BL0, 292u)
REG32(CREATOR_SW_CFG_DEFAULT_BOOT_DATA_IN_PROD_EN, 296u)
REG32(CREATOR_SW_CFG_RMA_SPIN_EN, 300u)
REG32(CREATOR_SW_CFG_RMA_SPIN_CYCLES, 304u)
REG32(CREATOR_SW_CFG_RNG_REPCNT_THRESHOLDS, 308u)
REG32(CREATOR_SW_CFG_RNG_REPCNTS_THRESHOLDS, 312u)
REG32(CREATOR_SW_CFG_RNG_ADAPTP_HI_THRESHOLDS, 316u)
REG32(CREATOR_SW_CFG_RNG_ADAPTP_LO_THRESHOLDS, 320u)
REG32(CREATOR_SW_CFG_RNG_BUCKET_THRESHOLDS, 324u)
REG32(CREATOR_SW_CFG_RNG_MARKOV_HI_THRESHOLDS, 328u)
REG32(CREATOR_SW_CFG_RNG_MARKOV_LO_THRESHOLDS, 332u)
REG32(CREATOR_SW_CFG_RNG_EXTHT_HI_THRESHOLDS, 336u)
REG32(CREATOR_SW_CFG_RNG_EXTHT_LO_THRESHOLDS, 340u)
REG32(CREATOR_SW_CFG_RNG_ALERT_THRESHOLD, 344u)
REG32(CREATOR_SW_CFG_RNG_HEALTH_CONFIG_DIGEST, 348u)
REG32(CREATOR_SW_CFG_SRAM_KEY_RENEW_EN, 352u)
REG32(CREATOR_SW_CFG_DIGEST, 360u)
REG32(OWNER_SW_CFG_ROM_ERROR_REPORTING, 368u)
REG32(OWNER_SW_CFG_ROM_BOOTSTRAP_DIS, 372u)
REG32(OWNER_SW_CFG_ROM_ALERT_CLASS_EN, 376u)
REG32(OWNER_SW_CFG_ROM_ALERT_ESCALATION, 380u)
REG32(OWNER_SW_CFG_ROM_ALERT_CLASSIFICATION, 384u)
REG32(OWNER_SW_CFG_ROM_LOCAL_ALERT_CLASSIFICATION, 804u)
REG32(OWNER_SW_CFG_ROM_ALERT_ACCUM_THRESH, 832u)
REG32(OWNER_SW_CFG_ROM_ALERT_TIMEOUT_CYCLES, 848u)
REG32(OWNER_SW_CFG_ROM_ALERT_PHASE_CYCLES, 864u)
REG32(OWNER_SW_CFG_ROM_ALERT_DIGEST_PROD, 928u)
REG32(OWNER_SW_CFG_ROM_ALERT_DIGEST_PROD_END, 932u)
REG32(OWNER_SW_CFG_ROM_ALERT_DIGEST_DEV, 936u)
REG32(OWNER_SW_CFG_ROM_ALERT_DIGEST_RMA, 940u)
REG32(OWNER_SW_CFG_ROM_WATCHDOG_BITE_THRESHOLD_CYCLES, 944u)
REG32(OWNER_SW_CFG_ROM_KEYMGR_ROM_EXT_MEAS_EN, 948u)
REG32(OWNER_SW_CFG_MANUF_STATE, 952u)
REG32(OWNER_SW_CFG_ROM_RSTMGR_INFO_EN, 956u)
REG32(OWNER_SW_CFG_DIGEST, 960u)
REG32(OWNERSHIP_SLOT_STATE_ROT_OWNER_AUTH, 968u)
REG32(OWNERSHIP_SLOT_STATE_PLAT_INTEG_AUTH, 984u)
REG32(OWNERSHIP_SLOT_STATE_PLAT_OWNER_AUTH, 1000u)
REG32(ROT_CREATOR_AUTH_NON_RAW_MFW_CODESIGN_KEY, 1016u)
REG32(ROT_CREATOR_AUTH_OWNERSHIP_STATE, 1176u)
REG32(ROT_CREATOR_AUTH_ROM2_PATCH_SIGVERIFY_KEY, 1180u)
REG32(ROT_CREATOR_AUTH_KEYMANIFEST_KEY, 1340u)
REG32(ROT_CREATOR_AUTH_UNLOCK4XFER_KEY, 1500u)
REG32(ROT_CREATOR_AUTH_IDENTITY_CERT, 1660u)
REG32(ROT_CREATOR_AUTH_DIGEST, 2432u)
REG32(ROT_OWNER_AUTH_SLOT0_KEYMANIFEST_KEY, 2440u)
REG32(ROT_OWNER_AUTH_SLOT0_UNLOCK4XFER_KEY, 2600u)
REG32(ROT_OWNER_AUTH_SLOT0_DIGEST, 2760u)
REG32(ROT_OWNER_AUTH_SLOT1_KEYMANIFEST_KEY, 2768u)
REG32(ROT_OWNER_AUTH_SLOT1_UNLOCK4XFER_KEY, 2928u)
REG32(ROT_OWNER_AUTH_SLOT1_DIGEST, 3088u)
REG32(PLAT_INTEG_AUTH_SLOT0_KEYMANIFEST_KEY, 3096u)
REG32(PLAT_INTEG_AUTH_SLOT0_UNLOCK4XFER_KEY, 3256u)
REG32(PLAT_INTEG_AUTH_SLOT0_DIGEST, 3416u)
REG32(PLAT_INTEG_AUTH_SLOT1_KEYMANIFEST_KEY, 3424u)
REG32(PLAT_INTEG_AUTH_SLOT1_UNLOCK4XFER_KEY, 3584u)
REG32(PLAT_INTEG_AUTH_SLOT1_DIGEST, 3744u)
REG32(PLAT_OWNER_AUTH_SLOT0_KEYMANIFEST_KEY, 3752u)
REG32(PLAT_OWNER_AUTH_SLOT0_UNLOCK4XFER_KEY, 3912u)
REG32(PLAT_OWNER_AUTH_SLOT0_DIGEST, 4072u)
REG32(PLAT_OWNER_AUTH_SLOT1_KEYMANIFEST_KEY, 4080u)
REG32(PLAT_OWNER_AUTH_SLOT1_UNLOCK4XFER_KEY, 4240u)
REG32(PLAT_OWNER_AUTH_SLOT1_DIGEST, 4400u)
REG32(PLAT_OWNER_AUTH_SLOT2_KEYMANIFEST_KEY, 4408u)
REG32(PLAT_OWNER_AUTH_SLOT2_UNLOCK4XFER_KEY, 4568u)
REG32(PLAT_OWNER_AUTH_SLOT2_DIGEST, 4728u)
REG32(PLAT_OWNER_AUTH_SLOT3_KEYMANIFEST_KEY, 4736u)
REG32(PLAT_OWNER_AUTH_SLOT3_UNLOCK4XFER_KEY, 4896u)
REG32(PLAT_OWNER_AUTH_SLOT3_DIGEST, 5056u)
REG32(EXT_NVM_ANTIREPLAY_FRESHNESS_CNT, 5064u)
REG32(ROM_PATCH_DATA, 6088u)
REG32(ROM_PATCH_DIGEST, 15944u)
REG32(HW_CFG0_DEVICE_ID, 15952u)
REG32(HW_CFG0_MANUF_STATE, 15984u)
REG32(HW_CFG0_DIGEST, 16016u)
REG32(HW_CFG1_SOC_DBG_STATE, 16024u)
REG32(HW_CFG1_EN_CSRNG_SW_APP_READ, 16028u)
REG32(HW_CFG1_EN_SRAM_IFETCH, 16029u)
REG32(HW_CFG1_DIGEST, 16032u)
REG32(SECRET0_TEST_UNLOCK_TOKEN, 16040u)
REG32(SECRET0_TEST_EXIT_TOKEN, 16056u)
REG32(SECRET0_DIGEST, 16072u)
REG32(SECRET0_ZER, 16080u)
REG32(SECRET1_SRAM_DATA_KEY_SEED, 16088u)
REG32(SECRET1_DIGEST, 16104u)
REG32(SECRET1_ZER, 16112u)
REG32(SECRET2_RMA_TOKEN, 16120u)
REG32(SECRET2_CREATOR_ROOT_KEY_SHARE0, 16136u)
REG32(SECRET2_CREATOR_ROOT_KEY_SHARE1, 16168u)
REG32(SECRET2_CREATOR_SEED, 16200u)
REG32(SECRET2_DIGEST, 16232u)
REG32(SECRET2_ZER, 16240u)
REG32(SECRET3_OWNER_SEED, 16248u)
REG32(SECRET3_DIGEST, 16280u)
REG32(SECRET3_ZER, 16288u)
REG32(LC_TRANSITION_CNT, 16296u)
REG32(LC_STATE, 16344u)
/* clang-format on */

#define VENDOR_TEST_SCRATCH_SIZE                             56u
#define CREATOR_SW_CFG_AST_CFG_SIZE                          124u
#define CREATOR_SW_CFG_AST_INIT_EN_SIZE                      4u
#define CREATOR_SW_CFG_OVERRIDES_SIZE                        32u
#define CREATOR_SW_CFG_ROM_EXT_SKU_SIZE                      4u
#define CREATOR_SW_CFG_SIGVERIFY_RSA_MOD_EXP_IBEX_EN_SIZE    4u
#define CREATOR_SW_CFG_SIGVERIFY_RSA_KEY_EN_SIZE             8u
#define CREATOR_SW_CFG_SIGVERIFY_SPX_EN_SIZE                 4u
#define CREATOR_SW_CFG_SIGVERIFY_SPX_KEY_EN_SIZE             8u
#define CREATOR_SW_CFG_FLASH_DATA_DEFAULT_CFG_SIZE           4u
#define CREATOR_SW_CFG_FLASH_INFO_BOOT_DATA_CFG_SIZE         4u
#define CREATOR_SW_CFG_FLASH_HW_INFO_CFG_OVERRIDE_SIZE       4u
#define CREATOR_SW_CFG_RNG_EN_SIZE                           4u
#define CREATOR_SW_CFG_JITTER_EN_SIZE                        4u
#define CREATOR_SW_CFG_RET_RAM_RESET_MASK_SIZE               4u
#define CREATOR_SW_CFG_MANUF_STATE_SIZE                      4u
#define CREATOR_SW_CFG_ROM_EXEC_EN_SIZE                      4u
#define CREATOR_SW_CFG_CPUCTRL_SIZE                          4u
#define CREATOR_SW_CFG_MIN_SEC_VER_ROM_EXT_SIZE              4u
#define CREATOR_SW_CFG_MIN_SEC_VER_BL0_SIZE                  4u
#define CREATOR_SW_CFG_DEFAULT_BOOT_DATA_IN_PROD_EN_SIZE     4u
#define CREATOR_SW_CFG_RMA_SPIN_EN_SIZE                      4u
#define CREATOR_SW_CFG_RMA_SPIN_CYCLES_SIZE                  4u
#define CREATOR_SW_CFG_RNG_REPCNT_THRESHOLDS_SIZE            4u
#define CREATOR_SW_CFG_RNG_REPCNTS_THRESHOLDS_SIZE           4u
#define CREATOR_SW_CFG_RNG_ADAPTP_HI_THRESHOLDS_SIZE         4u
#define CREATOR_SW_CFG_RNG_ADAPTP_LO_THRESHOLDS_SIZE         4u
#define CREATOR_SW_CFG_RNG_BUCKET_THRESHOLDS_SIZE            4u
#define CREATOR_SW_CFG_RNG_MARKOV_HI_THRESHOLDS_SIZE         4u
#define CREATOR_SW_CFG_RNG_MARKOV_LO_THRESHOLDS_SIZE         4u
#define CREATOR_SW_CFG_RNG_EXTHT_HI_THRESHOLDS_SIZE          4u
#define CREATOR_SW_CFG_RNG_EXTHT_LO_THRESHOLDS_SIZE          4u
#define CREATOR_SW_CFG_RNG_ALERT_THRESHOLD_SIZE              4u
#define CREATOR_SW_CFG_RNG_HEALTH_CONFIG_DIGEST_SIZE         4u
#define CREATOR_SW_CFG_SRAM_KEY_RENEW_EN_SIZE                4u
#define OWNER_SW_CFG_ROM_ERROR_REPORTING_SIZE                4u
#define OWNER_SW_CFG_ROM_BOOTSTRAP_DIS_SIZE                  4u
#define OWNER_SW_CFG_ROM_ALERT_CLASS_EN_SIZE                 4u
#define OWNER_SW_CFG_ROM_ALERT_ESCALATION_SIZE               4u
#define OWNER_SW_CFG_ROM_ALERT_CLASSIFICATION_SIZE           420u
#define OWNER_SW_CFG_ROM_LOCAL_ALERT_CLASSIFICATION_SIZE     28u
#define OWNER_SW_CFG_ROM_ALERT_ACCUM_THRESH_SIZE             16u
#define OWNER_SW_CFG_ROM_ALERT_TIMEOUT_CYCLES_SIZE           16u
#define OWNER_SW_CFG_ROM_ALERT_PHASE_CYCLES_SIZE             64u
#define OWNER_SW_CFG_ROM_ALERT_DIGEST_PROD_SIZE              4u
#define OWNER_SW_CFG_ROM_ALERT_DIGEST_PROD_END_SIZE          4u
#define OWNER_SW_CFG_ROM_ALERT_DIGEST_DEV_SIZE               4u
#define OWNER_SW_CFG_ROM_ALERT_DIGEST_RMA_SIZE               4u
#define OWNER_SW_CFG_ROM_WATCHDOG_BITE_THRESHOLD_CYCLES_SIZE 4u
#define OWNER_SW_CFG_ROM_KEYMGR_ROM_EXT_MEAS_EN_SIZE         4u
#define OWNER_SW_CFG_MANUF_STATE_SIZE                        4u
#define OWNER_SW_CFG_ROM_RSTMGR_INFO_EN_SIZE                 4u
#define OWNERSHIP_SLOT_STATE_ROT_OWNER_AUTH_SIZE             16u
#define OWNERSHIP_SLOT_STATE_PLAT_INTEG_AUTH_SIZE            16u
#define OWNERSHIP_SLOT_STATE_PLAT_OWNER_AUTH_SIZE            16u
#define ROT_CREATOR_AUTH_NON_RAW_MFW_CODESIGN_KEY_SIZE       160u
#define ROT_CREATOR_AUTH_OWNERSHIP_STATE_SIZE                4u
#define ROT_CREATOR_AUTH_ROM2_PATCH_SIGVERIFY_KEY_SIZE       160u
#define ROT_CREATOR_AUTH_KEYMANIFEST_KEY_SIZE                160u
#define ROT_CREATOR_AUTH_UNLOCK4XFER_KEY_SIZE                160u
#define ROT_CREATOR_AUTH_IDENTITY_CERT_SIZE                  768u
#define ROT_OWNER_AUTH_SLOT0_KEYMANIFEST_KEY_SIZE            160u
#define ROT_OWNER_AUTH_SLOT0_UNLOCK4XFER_KEY_SIZE            160u
#define ROT_OWNER_AUTH_SLOT1_SIZE                            328u
#define ROT_OWNER_AUTH_SLOT1_KEYMANIFEST_KEY_SIZE            160u
#define ROT_OWNER_AUTH_SLOT1_UNLOCK4XFER_KEY_SIZE            160u
#define PLAT_INTEG_AUTH_SLOT0_SIZE                           328u
#define PLAT_INTEG_AUTH_SLOT0_KEYMANIFEST_KEY_SIZE           160u
#define PLAT_INTEG_AUTH_SLOT0_UNLOCK4XFER_KEY_SIZE           160u
#define PLAT_INTEG_AUTH_SLOT1_SIZE                           328u
#define PLAT_INTEG_AUTH_SLOT1_KEYMANIFEST_KEY_SIZE           160u
#define PLAT_INTEG_AUTH_SLOT1_UNLOCK4XFER_KEY_SIZE           160u
#define PLAT_OWNER_AUTH_SLOT0_SIZE                           328u
#define PLAT_OWNER_AUTH_SLOT0_KEYMANIFEST_KEY_SIZE           160u
#define PLAT_OWNER_AUTH_SLOT0_UNLOCK4XFER_KEY_SIZE           160u
#define PLAT_OWNER_AUTH_SLOT1_SIZE                           328u
#define PLAT_OWNER_AUTH_SLOT1_KEYMANIFEST_KEY_SIZE           160u
#define PLAT_OWNER_AUTH_SLOT1_UNLOCK4XFER_KEY_SIZE           160u
#define PLAT_OWNER_AUTH_SLOT2_SIZE                           328u
#define PLAT_OWNER_AUTH_SLOT2_KEYMANIFEST_KEY_SIZE           160u
#define PLAT_OWNER_AUTH_SLOT2_UNLOCK4XFER_KEY_SIZE           160u
#define PLAT_OWNER_AUTH_SLOT3_SIZE                           328u
#define PLAT_OWNER_AUTH_SLOT3_KEYMANIFEST_KEY_SIZE           160u
#define PLAT_OWNER_AUTH_SLOT3_UNLOCK4XFER_KEY_SIZE           160u
#define EXT_NVM_ANTIREPLAY_FRESHNESS_CNT_SIZE                1024u
#define ROM_PATCH_DATA_SIZE                                  9192u
#define HW_CFG0_DEVICE_ID_SIZE                               32u
#define HW_CFG0_MANUF_STATE_SIZE                             32u
#define HW_CFG1_SOC_DBG_STATE_SIZE                           4u
#define HW_CFG1_EN_CSRNG_SW_APP_READ_SIZE                    1u
#define HW_CFG1_EN_SRAM_IFETCH_SIZE                          1u
#define SECRET0_TEST_UNLOCK_TOKEN_SIZE                       16u
#define SECRET0_TEST_EXIT_TOKEN_SIZE                         16u
#define SECRET1_SRAM_DATA_KEY_SEED_SIZE                      16u
#define SECRET2_RMA_TOKEN_SIZE                               16u
#define SECRET2_CREATOR_ROOT_KEY_SHARE0_SIZE                 32u
#define SECRET2_CREATOR_ROOT_KEY_SHARE1_SIZE                 32u
#define SECRET2_CREATOR_SEED_SIZE                            32u
#define SECRET3_OWNER_SEED_SIZE                              32u

#define SW_CFG_WINDOW_OFFSET 0x4000u
#define SW_CFG_WINDOW_SIZE   (NUM_SW_CFG_WINDOW_WORDS * sizeof(uint32_t))

#define R_LAST_REG (R_SECRET3_DIGEST_1)
#define REGS_COUNT (R_LAST_REG + 1u)
#define REGS_SIZE  (REGS_COUNT * sizeof(uint32_t))
#define REG_NAME(_reg_) \
    ((((_reg_) <= REGS_COUNT) && REG_NAMES[_reg_]) ? REG_NAMES[_reg_] : "?")

typedef enum {
    OTP_PART_VENDOR_TEST,
    OTP_PART_CREATOR_SW_CFG,
    OTP_PART_OWNER_SW_CFG,
    OTP_PART_OWNERSHIP_SLOT_STATE,
    OTP_PART_ROT_CREATOR_AUTH,
    OTP_PART_ROT_OWNER_AUTH_SLOT0,
    OTP_PART_ROT_OWNER_AUTH_SLOT1,
    OTP_PART_PLAT_INTEG_AUTH_SLOT0,
    OTP_PART_PLAT_INTEG_AUTH_SLOT1,
    OTP_PART_PLAT_OWNER_AUTH_SLOT0,
    OTP_PART_PLAT_OWNER_AUTH_SLOT1,
    OTP_PART_PLAT_OWNER_AUTH_SLOT2,
    OTP_PART_PLAT_OWNER_AUTH_SLOT3,
    OTP_PART_EXT_NVM,
    OTP_PART_ROM_PATCH,
    OTP_PART_HW_CFG0,
    OTP_PART_HW_CFG1,
    OTP_PART_SECRET0,
    OTP_PART_SECRET1,
    OTP_PART_SECRET2,
    OTP_PART_SECRET3,
    OTP_PART_LIFE_CYCLE,
    OTP_PART_OTP_COUNT, /* count of "real" OTP partitions */
    OTP_ENTRY_DAI = OTP_PART_OTP_COUNT, /* Fake partitions for error (...) */
    OTP_ENTRY_KDI, /* Key derivation issue, not really OTP */
    OTP_ENTRY_COUNT,
} OtOTPPartitionType;

static_assert(OTP_PART_OTP_COUNT == NUM_PART, "Invalid partition count");
#define OT_OTP_DJ_PARTS

/* NOLINTNEXTLINE */
#include "ot_otp_dj_parts.c"

static_assert(OTP_PART_OTP_COUNT == OTP_PART_COUNT, "Invalid partition count");
static_assert(OTP_PART_COUNT <= 64, "Maximum part count reached");

static_assert(OTP_BYTE_ADDR_WIDTH == R_DIRECT_ACCESS_ADDRESS_ADDRESS_LENGTH,
              "OTP byte address width mismatch");

struct OtOTPDjState {
    OtOTPEngineState parent_obj;

    struct {
        MemoryRegion ctrl;
        struct {
            MemoryRegion regs;
            MemoryRegion swcfg;
        } sub;
    } mmio;
};

struct OtOTPDjClass {
    OtOTPEngineClass parent_class;
    ResettablePhases parent_phases;
};

#define REG_NAME_ENTRY(_reg_) [R_##_reg_] = stringify(_reg_)
static const char *REG_NAMES[REGS_COUNT] = {
    /* clang-format off */
    REG_NAME_ENTRY(INTR_STATE),
    REG_NAME_ENTRY(INTR_ENABLE),
    REG_NAME_ENTRY(INTR_TEST),
    REG_NAME_ENTRY(ALERT_TEST),
    REG_NAME_ENTRY(STATUS),
    REG_NAME_ENTRY(ERR_CODE_0),
    REG_NAME_ENTRY(ERR_CODE_1),
    REG_NAME_ENTRY(ERR_CODE_2),
    REG_NAME_ENTRY(ERR_CODE_3),
    REG_NAME_ENTRY(ERR_CODE_4),
    REG_NAME_ENTRY(ERR_CODE_5),
    REG_NAME_ENTRY(ERR_CODE_6),
    REG_NAME_ENTRY(ERR_CODE_7),
    REG_NAME_ENTRY(ERR_CODE_8),
    REG_NAME_ENTRY(ERR_CODE_9),
    REG_NAME_ENTRY(ERR_CODE_10),
    REG_NAME_ENTRY(ERR_CODE_11),
    REG_NAME_ENTRY(ERR_CODE_12),
    REG_NAME_ENTRY(ERR_CODE_13),
    REG_NAME_ENTRY(ERR_CODE_14),
    REG_NAME_ENTRY(ERR_CODE_15),
    REG_NAME_ENTRY(ERR_CODE_16),
    REG_NAME_ENTRY(ERR_CODE_17),
    REG_NAME_ENTRY(ERR_CODE_18),
    REG_NAME_ENTRY(ERR_CODE_19),
    REG_NAME_ENTRY(ERR_CODE_20),
    REG_NAME_ENTRY(ERR_CODE_21),
    REG_NAME_ENTRY(ERR_CODE_22),
    REG_NAME_ENTRY(ERR_CODE_23),
    REG_NAME_ENTRY(DIRECT_ACCESS_REGWEN),
    REG_NAME_ENTRY(DIRECT_ACCESS_CMD),
    REG_NAME_ENTRY(DIRECT_ACCESS_ADDRESS),
    REG_NAME_ENTRY(DIRECT_ACCESS_WDATA_0),
    REG_NAME_ENTRY(DIRECT_ACCESS_WDATA_1),
    REG_NAME_ENTRY(DIRECT_ACCESS_RDATA_0),
    REG_NAME_ENTRY(DIRECT_ACCESS_RDATA_1),
    REG_NAME_ENTRY(CHECK_TRIGGER_REGWEN),
    REG_NAME_ENTRY(CHECK_TRIGGER),
    REG_NAME_ENTRY(CHECK_REGWEN),
    REG_NAME_ENTRY(CHECK_TIMEOUT),
    REG_NAME_ENTRY(INTEGRITY_CHECK_PERIOD),
    REG_NAME_ENTRY(CONSISTENCY_CHECK_PERIOD),
    REG_NAME_ENTRY(VENDOR_TEST_READ_LOCK),
    REG_NAME_ENTRY(CREATOR_SW_CFG_READ_LOCK),
    REG_NAME_ENTRY(OWNER_SW_CFG_READ_LOCK),
    REG_NAME_ENTRY(OWNERSHIP_SLOT_STATE_READ_LOCK),
    REG_NAME_ENTRY(ROT_CREATOR_AUTH_READ_LOCK),
    REG_NAME_ENTRY(ROT_OWNER_AUTH_SLOT0_READ_LOCK),
    REG_NAME_ENTRY(ROT_OWNER_AUTH_SLOT1_READ_LOCK),
    REG_NAME_ENTRY(PLAT_INTEG_AUTH_SLOT0_READ_LOCK),
    REG_NAME_ENTRY(PLAT_INTEG_AUTH_SLOT1_READ_LOCK),
    REG_NAME_ENTRY(PLAT_OWNER_AUTH_SLOT0_READ_LOCK),
    REG_NAME_ENTRY(PLAT_OWNER_AUTH_SLOT1_READ_LOCK),
    REG_NAME_ENTRY(PLAT_OWNER_AUTH_SLOT2_READ_LOCK),
    REG_NAME_ENTRY(PLAT_OWNER_AUTH_SLOT3_READ_LOCK),
    REG_NAME_ENTRY(EXT_NVM_READ_LOCK),
    REG_NAME_ENTRY(ROM_PATCH_READ_LOCK),
    REG_NAME_ENTRY(VENDOR_TEST_DIGEST_0),
    REG_NAME_ENTRY(VENDOR_TEST_DIGEST_1),
    REG_NAME_ENTRY(CREATOR_SW_CFG_DIGEST_0),
    REG_NAME_ENTRY(CREATOR_SW_CFG_DIGEST_1),
    REG_NAME_ENTRY(OWNER_SW_CFG_DIGEST_0),
    REG_NAME_ENTRY(OWNER_SW_CFG_DIGEST_1),
    REG_NAME_ENTRY(ROT_CREATOR_AUTH_DIGEST_0),
    REG_NAME_ENTRY(ROT_CREATOR_AUTH_DIGEST_1),
    REG_NAME_ENTRY(ROT_OWNER_AUTH_SLOT0_DIGEST_0),
    REG_NAME_ENTRY(ROT_OWNER_AUTH_SLOT0_DIGEST_1),
    REG_NAME_ENTRY(ROT_OWNER_AUTH_SLOT1_DIGEST_0),
    REG_NAME_ENTRY(ROT_OWNER_AUTH_SLOT1_DIGEST_1),
    REG_NAME_ENTRY(PLAT_INTEG_AUTH_SLOT0_DIGEST_0),
    REG_NAME_ENTRY(PLAT_INTEG_AUTH_SLOT0_DIGEST_1),
    REG_NAME_ENTRY(PLAT_INTEG_AUTH_SLOT1_DIGEST_0),
    REG_NAME_ENTRY(PLAT_INTEG_AUTH_SLOT1_DIGEST_1),
    REG_NAME_ENTRY(PLAT_OWNER_AUTH_SLOT0_DIGEST_0),
    REG_NAME_ENTRY(PLAT_OWNER_AUTH_SLOT0_DIGEST_1),
    REG_NAME_ENTRY(PLAT_OWNER_AUTH_SLOT1_DIGEST_0),
    REG_NAME_ENTRY(PLAT_OWNER_AUTH_SLOT1_DIGEST_1),
    REG_NAME_ENTRY(PLAT_OWNER_AUTH_SLOT2_DIGEST_0),
    REG_NAME_ENTRY(PLAT_OWNER_AUTH_SLOT2_DIGEST_1),
    REG_NAME_ENTRY(PLAT_OWNER_AUTH_SLOT3_DIGEST_0),
    REG_NAME_ENTRY(PLAT_OWNER_AUTH_SLOT3_DIGEST_1),
    REG_NAME_ENTRY(ROM_PATCH_DIGEST_0),
    REG_NAME_ENTRY(ROM_PATCH_DIGEST_1),
    REG_NAME_ENTRY(HW_CFG0_DIGEST_0),
    REG_NAME_ENTRY(HW_CFG0_DIGEST_1),
    REG_NAME_ENTRY(HW_CFG1_DIGEST_0),
    REG_NAME_ENTRY(HW_CFG1_DIGEST_1),
    REG_NAME_ENTRY(SECRET0_DIGEST_0),
    REG_NAME_ENTRY(SECRET0_DIGEST_1),
    REG_NAME_ENTRY(SECRET1_DIGEST_0),
    REG_NAME_ENTRY(SECRET1_DIGEST_1),
    REG_NAME_ENTRY(SECRET2_DIGEST_0),
    REG_NAME_ENTRY(SECRET2_DIGEST_1),
    REG_NAME_ENTRY(SECRET3_DIGEST_0),
    REG_NAME_ENTRY(SECRET3_DIGEST_1),
    /* clang-format on */
};
#undef REG_NAME_ENTRY

static const char *OTP_TOKEN_NAMES[] = {
    /* clang-format off */
    OTP_NAME_ENTRY(OTP_TOKEN_TEST_UNLOCK),
    OTP_NAME_ENTRY(OTP_TOKEN_TEST_EXIT),
    OTP_NAME_ENTRY(OTP_TOKEN_RMA),
    /* clang-format on */
};

#define OTP_TOKEN_NAME(_tk_) \
    ((unsigned)(_tk_) < ARRAY_SIZE(OTP_TOKEN_NAMES) ? \
         OTP_TOKEN_NAMES[(_tk_)] : \
         "?")

static uint32_t ot_otp_dj_get_status(const OtOTPEngineState *s)
{
    uint32_t status;

    status = FIELD_DP32(s->regs[R_STATUS], STATUS, DAI_IDLE,
                        !ot_otp_engine_dai_is_busy(s));

    return status;
}

static uint64_t ot_otp_dj_reg_read(void *opaque, hwaddr addr, unsigned size)
{
    OtOTPEngineState *s = OT_OTP_ENGINE(opaque);
    OtOTPEngineClass *c = OT_OTP_ENGINE_GET_CLASS(s);
    (void)size;
    uint32_t val32;

    hwaddr reg = R32_OFF(addr);
    switch (reg) {
    case R_INTR_STATE:
    case R_INTR_ENABLE:
    case R_ERR_CODE_0 ... R_ERR_CODE_23:
    case R_DIRECT_ACCESS_WDATA_0:
    case R_DIRECT_ACCESS_WDATA_1:
    case R_DIRECT_ACCESS_RDATA_0:
    case R_DIRECT_ACCESS_RDATA_1:
    case R_DIRECT_ACCESS_ADDRESS:
    case R_VENDOR_TEST_READ_LOCK ... R_ROM_PATCH_READ_LOCK:
    case R_CHECK_TRIGGER_REGWEN:
    case R_CHECK_REGWEN:
        val32 = s->regs[reg];
        break;
    case R_STATUS:
        val32 = ot_otp_dj_get_status(s);
        break;
    case R_DIRECT_ACCESS_REGWEN:
        /* disabled either if SW locked, or if DAI is busy. */
        val32 = s->regs[reg];
        val32 &= FIELD_DP32(0u, DIRECT_ACCESS_REGWEN, REGWEN,
                            (uint32_t)!ot_otp_engine_dai_is_busy(s));
        break;
    /* NOLINTNEXTLINE */
    case R_DIRECT_ACCESS_CMD:
    case R_CHECK_TRIGGER:
        val32 = 0; /* R0W1C */
        break;
    case R_CHECK_TIMEOUT:
    case R_INTEGRITY_CHECK_PERIOD:
    case R_CONSISTENCY_CHECK_PERIOD:
        /* @todo: not yet implemented, but these are R/W registers */
        qemu_log_mask(LOG_UNIMP, "%s: %s: %s is not supported\n", __func__,
                      s->ot_id, REG_NAME(reg));
        val32 = s->regs[reg];
        break;
    case R_VENDOR_TEST_DIGEST_0 ... R_SECRET3_DIGEST_1:
        /*
         * In all partitions with a digest, the digest itself is ALWAYS
         * readable.
         */
        val32 = c->get_part_digest_reg(s, reg - R_VENDOR_TEST_DIGEST_0);
        break;
    case R_INTR_TEST:
    case R_ALERT_TEST:
        qemu_log_mask(LOG_GUEST_ERROR,
                      "%s: %s: W/O register 0x02%" HWADDR_PRIx " (%s)\n",
                      __func__, s->ot_id, addr, REG_NAME(reg));
        val32 = 0;
        break;
    default:
        qemu_log_mask(LOG_GUEST_ERROR,
                      "%s: %s: Bad offset 0x%" HWADDR_PRIx "\n", __func__,
                      s->ot_id, addr);
        val32 = 0;
        break;
    }

    uint32_t pc = ibex_get_current_pc();
    trace_ot_otp_io_reg_read_out(s->ot_id, (uint32_t)addr, REG_NAME(reg), val32,
                                 pc);

    return (uint64_t)val32;
}

static void ot_otp_dj_reg_write(void *opaque, hwaddr addr, uint64_t value,
                                unsigned size)
{
    OtOTPEngineState *s = OT_OTP_ENGINE(opaque);
    OtOTPEngineClass *c = OT_OTP_ENGINE_GET_CLASS(s);
    (void)size;
    uint32_t val32 = (uint32_t)value;

    hwaddr reg = R32_OFF(addr);

    uint32_t pc = ibex_get_current_pc();

    trace_ot_otp_io_reg_write(s->ot_id, (uint32_t)addr, REG_NAME(reg), val32,
                              pc);

    switch (reg) {
    case R_DIRECT_ACCESS_CMD:
    case R_DIRECT_ACCESS_ADDRESS:
    case R_DIRECT_ACCESS_WDATA_0:
    case R_DIRECT_ACCESS_WDATA_1:
    case R_VENDOR_TEST_READ_LOCK ... R_ROM_PATCH_READ_LOCK:
        if (!(s->regs[R_DIRECT_ACCESS_REGWEN] &
              R_DIRECT_ACCESS_REGWEN_REGWEN_MASK)) {
            qemu_log_mask(LOG_GUEST_ERROR,
                          "%s: %s: %s is not enabled, %s is protected\n",
                          __func__, s->ot_id, REG_NAME(R_DIRECT_ACCESS_REGWEN),
                          REG_NAME(reg));
            return;
        }
        break;
    case R_CHECK_TRIGGER:
        if (!(s->regs[R_CHECK_TRIGGER_REGWEN] &
              R_CHECK_TRIGGER_REGWEN_REGWEN_MASK)) {
            qemu_log_mask(LOG_GUEST_ERROR,
                          "%s: %s: %s is not enabled, %s is protected\n",
                          __func__, s->ot_id, REG_NAME(R_CHECK_TRIGGER_REGWEN),
                          REG_NAME(reg));
            return;
        }
        break;
    case R_CHECK_TIMEOUT:
    case R_INTEGRITY_CHECK_PERIOD:
    case R_CONSISTENCY_CHECK_PERIOD:
        if (!(s->regs[R_CHECK_REGWEN] & R_CHECK_REGWEN_REGWEN_MASK)) {
            qemu_log_mask(LOG_GUEST_ERROR,
                          "%s: %s: %s is not enabled, %s is protected\n",
                          __func__, s->ot_id, REG_NAME(R_CHECK_REGWEN),
                          REG_NAME(reg));
            return;
        }
        break;
    case R_STATUS:
    case R_ERR_CODE_0 ... R_ERR_CODE_23:
    case R_DIRECT_ACCESS_RDATA_0:
    case R_DIRECT_ACCESS_RDATA_1:
    case R_VENDOR_TEST_DIGEST_0 ... R_SECRET3_DIGEST_1:
        qemu_log_mask(LOG_GUEST_ERROR,
                      "%s: %s: R/O register 0x%03" HWADDR_PRIx " (%s)\n",
                      __func__, s->ot_id, addr, REG_NAME(reg));
        return;
    default:
        break;
    }

    switch (reg) {
    case R_INTR_STATE:
        val32 &= INTR_WMASK;
        s->regs[R_INTR_STATE] &= ~val32; /* RW1C */
        c->update_irqs(s);
        break;
    case R_INTR_ENABLE:
        val32 &= INTR_WMASK;
        s->regs[R_INTR_ENABLE] = val32;
        c->update_irqs(s);
        break;
    case R_INTR_TEST:
        val32 &= INTR_WMASK;
        s->regs[R_INTR_STATE] = val32;
        c->update_irqs(s);
        break;
    case R_ALERT_TEST:
        val32 &= ALERT_WMASK;
        s->regs[reg] = val32;
        c->update_alerts(s);
        break;
    case R_DIRECT_ACCESS_REGWEN:
        val32 &= R_DIRECT_ACCESS_REGWEN_REGWEN_MASK;
        s->regs[reg] &= val32; /* RW0C */
        break;
    case R_DIRECT_ACCESS_CMD:
        if (FIELD_EX32(val32, DIRECT_ACCESS_CMD, RD)) {
            c->dai_read(s);
        } else if (FIELD_EX32(val32, DIRECT_ACCESS_CMD, WR)) {
            c->dai_write(s);
        } else if (FIELD_EX32(val32, DIRECT_ACCESS_CMD, DIGEST)) {
            c->dai_digest(s);
        }
        /* @todo implement ZEROIZE command */
        break;
    case R_DIRECT_ACCESS_ADDRESS:
        val32 &= R_DIRECT_ACCESS_ADDRESS_ADDRESS_MASK;
        s->regs[reg] = val32;
        break;
    case R_DIRECT_ACCESS_WDATA_0:
    case R_DIRECT_ACCESS_WDATA_1:
        s->regs[reg] = val32;
        break;
    case R_VENDOR_TEST_READ_LOCK ... R_ROM_PATCH_READ_LOCK:
        val32 &= READ_LOCK_MASK;
        s->regs[reg] &= val32; /* RW0C */
        break;
    case R_CHECK_TRIGGER_REGWEN:
        val32 &= R_CHECK_TRIGGER_REGWEN_REGWEN_MASK;
        s->regs[reg] &= val32; /* RW0C */
        break;
    case R_CHECK_REGWEN:
        val32 &= R_CHECK_REGWEN_REGWEN_MASK;
        s->regs[reg] &= val32; /* RW0C */
        break;
    case R_CHECK_TRIGGER:
    case R_CHECK_TIMEOUT:
    case R_INTEGRITY_CHECK_PERIOD:
    case R_CONSISTENCY_CHECK_PERIOD:
        qemu_log_mask(LOG_UNIMP, "%s: %s: %s is not supported\n", __func__,
                      s->ot_id, REG_NAME(reg));
        break;
    default:
        qemu_log_mask(LOG_GUEST_ERROR,
                      "%s: %s: Bad offset 0x%" HWADDR_PRIx "\n", __func__,
                      s->ot_id, addr);
        break;
    }
}

static const char *ot_otp_dj_swcfg_reg_name(unsigned swreg)
{
#define CASE_BYTE(_reg_) \
    case A_##_reg_: \
        return stringify(_reg_)
#define CASE_SUB(_reg_, _sz_) \
    case A_##_reg_...(A_##_reg_ + (_sz_) - 1u): \
        return stringify(_reg_)
#define CASE_REG(_reg_) \
    case A_##_reg_...(A_##_reg_ + 3u): \
        return stringify(_reg_)
#define CASE_WIDE(_reg_) \
    case A_##_reg_...(A_##_reg_ + 7u): \
        return stringify(_reg_)
#define CASE_RANGE(_reg_) \
    case A_##_reg_...(A_##_reg_ + (_reg_##_SIZE) - 1u): \
        return stringify(_reg_)

    switch (swreg) {
        CASE_RANGE(VENDOR_TEST_SCRATCH);
        CASE_WIDE(VENDOR_TEST_DIGEST);
        CASE_RANGE(CREATOR_SW_CFG_AST_CFG);
        CASE_REG(CREATOR_SW_CFG_AST_INIT_EN);
        CASE_RANGE(CREATOR_SW_CFG_OVERRIDES);
        CASE_REG(CREATOR_SW_CFG_ROM_EXT_SKU);
        CASE_REG(CREATOR_SW_CFG_SIGVERIFY_RSA_MOD_EXP_IBEX_EN);
        CASE_RANGE(CREATOR_SW_CFG_SIGVERIFY_RSA_KEY_EN);
        CASE_REG(CREATOR_SW_CFG_SIGVERIFY_SPX_EN);
        CASE_RANGE(CREATOR_SW_CFG_SIGVERIFY_SPX_KEY_EN);
        CASE_REG(CREATOR_SW_CFG_FLASH_DATA_DEFAULT_CFG);
        CASE_REG(CREATOR_SW_CFG_FLASH_INFO_BOOT_DATA_CFG);
        CASE_REG(CREATOR_SW_CFG_FLASH_HW_INFO_CFG_OVERRIDE);
        CASE_REG(CREATOR_SW_CFG_RNG_EN);
        CASE_REG(CREATOR_SW_CFG_JITTER_EN);
        CASE_REG(CREATOR_SW_CFG_RET_RAM_RESET_MASK);
        CASE_REG(CREATOR_SW_CFG_MANUF_STATE);
        CASE_REG(CREATOR_SW_CFG_ROM_EXEC_EN);
        CASE_REG(CREATOR_SW_CFG_CPUCTRL);
        CASE_REG(CREATOR_SW_CFG_MIN_SEC_VER_ROM_EXT);
        CASE_REG(CREATOR_SW_CFG_MIN_SEC_VER_BL0);
        CASE_REG(CREATOR_SW_CFG_DEFAULT_BOOT_DATA_IN_PROD_EN);
        CASE_REG(CREATOR_SW_CFG_RMA_SPIN_EN);
        CASE_REG(CREATOR_SW_CFG_RMA_SPIN_CYCLES);
        CASE_REG(CREATOR_SW_CFG_RNG_REPCNT_THRESHOLDS);
        CASE_REG(CREATOR_SW_CFG_RNG_REPCNTS_THRESHOLDS);
        CASE_REG(CREATOR_SW_CFG_RNG_ADAPTP_HI_THRESHOLDS);
        CASE_REG(CREATOR_SW_CFG_RNG_ADAPTP_LO_THRESHOLDS);
        CASE_REG(CREATOR_SW_CFG_RNG_BUCKET_THRESHOLDS);
        CASE_REG(CREATOR_SW_CFG_RNG_MARKOV_HI_THRESHOLDS);
        CASE_REG(CREATOR_SW_CFG_RNG_MARKOV_LO_THRESHOLDS);
        CASE_REG(CREATOR_SW_CFG_RNG_EXTHT_HI_THRESHOLDS);
        CASE_REG(CREATOR_SW_CFG_RNG_EXTHT_LO_THRESHOLDS);
        CASE_REG(CREATOR_SW_CFG_RNG_ALERT_THRESHOLD);
        CASE_REG(CREATOR_SW_CFG_RNG_HEALTH_CONFIG_DIGEST);
        CASE_REG(CREATOR_SW_CFG_SRAM_KEY_RENEW_EN);
        CASE_WIDE(CREATOR_SW_CFG_DIGEST);
        CASE_REG(OWNER_SW_CFG_ROM_ERROR_REPORTING);
        CASE_REG(OWNER_SW_CFG_ROM_BOOTSTRAP_DIS);
        CASE_REG(OWNER_SW_CFG_ROM_ALERT_CLASS_EN);
        CASE_REG(OWNER_SW_CFG_ROM_ALERT_ESCALATION);
        CASE_RANGE(OWNER_SW_CFG_ROM_ALERT_CLASSIFICATION);
        CASE_RANGE(OWNER_SW_CFG_ROM_LOCAL_ALERT_CLASSIFICATION);
        CASE_RANGE(OWNER_SW_CFG_ROM_ALERT_ACCUM_THRESH);
        CASE_RANGE(OWNER_SW_CFG_ROM_ALERT_TIMEOUT_CYCLES);
        CASE_RANGE(OWNER_SW_CFG_ROM_ALERT_PHASE_CYCLES);
        CASE_REG(OWNER_SW_CFG_ROM_ALERT_DIGEST_PROD);
        CASE_REG(OWNER_SW_CFG_ROM_ALERT_DIGEST_PROD_END);
        CASE_REG(OWNER_SW_CFG_ROM_ALERT_DIGEST_DEV);
        CASE_REG(OWNER_SW_CFG_ROM_ALERT_DIGEST_RMA);
        CASE_REG(OWNER_SW_CFG_ROM_WATCHDOG_BITE_THRESHOLD_CYCLES);
        CASE_REG(OWNER_SW_CFG_ROM_KEYMGR_ROM_EXT_MEAS_EN);
        CASE_REG(OWNER_SW_CFG_MANUF_STATE);
        CASE_REG(OWNER_SW_CFG_ROM_RSTMGR_INFO_EN);
        CASE_WIDE(OWNER_SW_CFG_DIGEST);
        CASE_RANGE(OWNERSHIP_SLOT_STATE_ROT_OWNER_AUTH);
        CASE_RANGE(OWNERSHIP_SLOT_STATE_PLAT_INTEG_AUTH);
        CASE_RANGE(OWNERSHIP_SLOT_STATE_PLAT_OWNER_AUTH);
        CASE_RANGE(ROT_CREATOR_AUTH_NON_RAW_MFW_CODESIGN_KEY);
        CASE_REG(ROT_CREATOR_AUTH_OWNERSHIP_STATE);
        CASE_RANGE(ROT_CREATOR_AUTH_ROM2_PATCH_SIGVERIFY_KEY);
        CASE_RANGE(ROT_CREATOR_AUTH_KEYMANIFEST_KEY);
        CASE_RANGE(ROT_CREATOR_AUTH_UNLOCK4XFER_KEY);
        CASE_RANGE(ROT_CREATOR_AUTH_IDENTITY_CERT);
        CASE_WIDE(ROT_CREATOR_AUTH_DIGEST);
        CASE_RANGE(ROT_OWNER_AUTH_SLOT0_KEYMANIFEST_KEY);
        CASE_RANGE(ROT_OWNER_AUTH_SLOT0_UNLOCK4XFER_KEY);
        CASE_WIDE(ROT_OWNER_AUTH_SLOT0_DIGEST);
        CASE_RANGE(ROT_OWNER_AUTH_SLOT1_KEYMANIFEST_KEY);
        CASE_RANGE(ROT_OWNER_AUTH_SLOT1_UNLOCK4XFER_KEY);
        CASE_WIDE(ROT_OWNER_AUTH_SLOT1_DIGEST);
        CASE_RANGE(PLAT_INTEG_AUTH_SLOT0_KEYMANIFEST_KEY);
        CASE_RANGE(PLAT_INTEG_AUTH_SLOT0_UNLOCK4XFER_KEY);
        CASE_WIDE(PLAT_INTEG_AUTH_SLOT0_DIGEST);
        CASE_RANGE(PLAT_INTEG_AUTH_SLOT1_KEYMANIFEST_KEY);
        CASE_RANGE(PLAT_INTEG_AUTH_SLOT1_UNLOCK4XFER_KEY);
        CASE_WIDE(PLAT_INTEG_AUTH_SLOT1_DIGEST);
        CASE_RANGE(PLAT_OWNER_AUTH_SLOT0_KEYMANIFEST_KEY);
        CASE_RANGE(PLAT_OWNER_AUTH_SLOT0_UNLOCK4XFER_KEY);
        CASE_WIDE(PLAT_OWNER_AUTH_SLOT0_DIGEST);
        CASE_RANGE(PLAT_OWNER_AUTH_SLOT1_KEYMANIFEST_KEY);
        CASE_RANGE(PLAT_OWNER_AUTH_SLOT1_UNLOCK4XFER_KEY);
        CASE_WIDE(PLAT_OWNER_AUTH_SLOT1_DIGEST);
        CASE_RANGE(PLAT_OWNER_AUTH_SLOT2_KEYMANIFEST_KEY);
        CASE_RANGE(PLAT_OWNER_AUTH_SLOT2_UNLOCK4XFER_KEY);
        CASE_WIDE(PLAT_OWNER_AUTH_SLOT2_DIGEST);
        CASE_RANGE(PLAT_OWNER_AUTH_SLOT3_KEYMANIFEST_KEY);
        CASE_RANGE(PLAT_OWNER_AUTH_SLOT3_UNLOCK4XFER_KEY);
        CASE_WIDE(PLAT_OWNER_AUTH_SLOT3_DIGEST);
        CASE_RANGE(EXT_NVM_ANTIREPLAY_FRESHNESS_CNT);
        CASE_RANGE(ROM_PATCH_DATA);
        CASE_WIDE(ROM_PATCH_DIGEST);
        CASE_RANGE(HW_CFG0_DEVICE_ID);
        CASE_RANGE(HW_CFG0_MANUF_STATE);
        CASE_WIDE(HW_CFG0_DIGEST);
        CASE_REG(HW_CFG1_SOC_DBG_STATE);
        CASE_BYTE(HW_CFG1_EN_CSRNG_SW_APP_READ);
        CASE_BYTE(HW_CFG1_EN_SRAM_IFETCH);
        CASE_WIDE(HW_CFG1_DIGEST);
        CASE_RANGE(SECRET0_TEST_UNLOCK_TOKEN);
        CASE_RANGE(SECRET0_TEST_EXIT_TOKEN);
        CASE_WIDE(SECRET0_DIGEST);
        CASE_WIDE(SECRET0_ZER);
        CASE_RANGE(SECRET1_SRAM_DATA_KEY_SEED);
        CASE_WIDE(SECRET1_DIGEST);
        CASE_WIDE(SECRET1_ZER);
        CASE_RANGE(SECRET2_RMA_TOKEN);
        CASE_RANGE(SECRET2_CREATOR_ROOT_KEY_SHARE0);
        CASE_RANGE(SECRET2_CREATOR_ROOT_KEY_SHARE1);
        CASE_RANGE(SECRET2_CREATOR_SEED);
        CASE_WIDE(SECRET2_DIGEST);
        CASE_WIDE(SECRET2_ZER);
        CASE_RANGE(SECRET3_OWNER_SEED);
        CASE_WIDE(SECRET3_DIGEST);
        CASE_WIDE(SECRET3_ZER);
        CASE_RANGE(LC_TRANSITION_CNT);
        CASE_RANGE(LC_STATE);
    default:
        return "<?>";
    }

#undef CASE_BYTE
#undef CASE_SUB
#undef CASE_REG
#undef CASE_RANGE
#undef CASE_DIGEST
}

static MemTxResult ot_otp_dj_swcfg_read_with_attrs(
    void *opaque, hwaddr addr, uint64_t *data, unsigned size, MemTxAttrs attrs)
{
    OtOTPEngineState *s = OT_OTP_ENGINE(opaque);
    OtOTPEngineClass *c = OT_OTP_ENGINE_GET_CLASS(s);
    (void)size;
    (void)attrs;

    hwaddr reg = R32_OFF(addr);
    int partition = c->get_part_from_address(s, addr);

    if (partition < 0) {
        trace_ot_otp_access_error_on(s->ot_id, partition, addr, "invalid");
        *data = 0ull;

        return MEMTX_DECODE_ERROR;
    }

    unsigned part_ix = (unsigned)partition;

    if (ot_otp_engine_is_buffered(s, part_ix)) {
        trace_ot_otp_access_error_on(s->ot_id, partition, addr, "buffered");
        c->set_error(s, part_ix, OTP_ACCESS_ERROR);

        /* real HW seems to stall the Tile Link bus in this case */
        return MEMTX_ACCESS_ERROR;
    }

    bool is_readable = c->is_readable(s, part_ix);
    bool is_digest = ot_otp_engine_is_part_digest_offset(s, part_ix, addr);
    bool is_zer = ot_otp_engine_is_part_zer_offset(s, part_ix, addr);

    if (!is_readable && !(is_digest || is_zer)) {
        trace_ot_otp_access_error_on(s->ot_id, partition, addr, "not readable");
        c->set_error(s, part_ix, OTP_ACCESS_ERROR);

        return MEMTX_DECODE_ERROR;
    }

    uint32_t val32 = s->otp->data[reg];
    c->set_error(s, part_ix, OTP_NO_ERROR);

    uint64_t pc;

    pc = ibex_get_current_pc();
    trace_ot_otp_io_swcfg_read_out(s->ot_id, (uint32_t)addr,
                                   ot_otp_dj_swcfg_reg_name(addr), val32, pc);

    *data = (uint64_t)val32;

    return MEMTX_OK;
}

static void ot_otp_dj_get_lc_info(
    const OtOTPIf *dev, uint16_t *lc_tcount, uint16_t *lc_state,
    uint8_t *lc_valid, uint8_t *secret_valid, const OtOTPTokens **tokens)
{
    const OtOTPEngineState *s = OT_OTP_ENGINE(dev);
    const OtOTPStorage *otp = s->otp;

    if (lc_tcount) {
        memcpy(lc_tcount, &otp->data[R_LC_TRANSITION_CNT],
               LC_TRANSITION_CNT_SIZE);
    }

    if (lc_state) {
        memcpy(lc_state, &otp->data[R_LC_STATE], LC_STATE_SIZE);
    }

    if (lc_valid) {
        *lc_valid = !(s->part_ctrls[OTP_PART_SECRET0].failed ||
                      s->part_ctrls[OTP_PART_SECRET2].failed ||
                      s->part_ctrls[s->part_lc_num].failed) ?
                        OT_MULTIBITBOOL_LC4_TRUE :
                        OT_MULTIBITBOOL_LC4_FALSE;
    }
    if (secret_valid) {
        *secret_valid = (!s->part_ctrls[OTP_PART_SECRET2].failed &&
                         s->part_ctrls[OTP_PART_SECRET2].locked) ?
                            OT_MULTIBITBOOL_LC4_TRUE :
                            OT_MULTIBITBOOL_LC4_FALSE;
    }
    if (tokens) {
        *tokens = s->tokens;
    }
}

static void ot_otp_dj_get_keymgr_secret(
    OtOTPIf *dev, OtOTPKeyMgrSecretType type, OtOTPKeyMgrSecret *secret)
{
    OtOTPEngineState *s = OT_OTP_ENGINE(dev);
    int partition;
    size_t offset;

    switch (type) {
    case OTP_KEYMGR_SECRET_CREATOR_ROOT_KEY_SHARE0:
        partition = OTP_PART_SECRET2;
        offset =
            A_SECRET2_CREATOR_ROOT_KEY_SHARE0 - s->part_descs[partition].offset;
        break;
    case OTP_KEYMGR_SECRET_CREATOR_ROOT_KEY_SHARE1:
        partition = OTP_PART_SECRET2;
        offset =
            A_SECRET2_CREATOR_ROOT_KEY_SHARE1 - s->part_descs[partition].offset;
        break;
    case OTP_KEYMGR_SECRET_CREATOR_SEED:
        partition = OTP_PART_SECRET2;
        offset = A_SECRET2_CREATOR_SEED - s->part_descs[partition].offset;
        break;
    case OTP_KEYMGR_SECRET_OWNER_SEED:
        partition = OTP_PART_SECRET3;
        offset = A_SECRET3_OWNER_SEED - s->part_descs[partition].offset;
        break;
    default:
        error_report("%s: %s: invalid OTP keymgr secret type: %d", __func__,
                     s->ot_id, type);
        secret->valid = false;
        memset(secret->secret, 0, OT_OTP_KEYMGR_SECRET_SIZE);
        return;
    }

    unsigned part_ix = (unsigned)partition;
    g_assert(ot_otp_engine_is_buffered(s, part_ix));

    const uint8_t *data_ptr;
    if (s->lc_broadcast.current_level & BIT(OT_OTP_LC_SEED_HW_RD_EN)) {
        data_ptr = (const uint8_t *)s->part_ctrls[part_ix].buffer.data;
    } else {
        /* source data from PartInvDefault instead of real buffer */
        data_ptr = s->inv_default_parts[part_ix];
    }

    secret->valid = s->part_ctrls[part_ix].digest != 0;
    memcpy(secret->secret, &data_ptr[offset], OT_OTP_KEYMGR_SECRET_SIZE);
}

static void
ot_otp_dj_update_status_error(OtOTPImplIf *dev, OtOTPStatus error, bool set)
{
    const OtOTPEngineState *s = OT_OTP_ENGINE(dev);

    uint32_t mask;
    switch (error) {
    case OT_OTP_STATUS_DAI:
        mask = R_STATUS_DAI_ERROR_MASK;
        break;
    case OT_OTP_STATUS_LCI:
        mask = R_STATUS_LCI_ERROR_MASK;
        break;
    default:
        g_assert_not_reached();
        return;
    }

    if (set) {
        s->regs[R_STATUS] |= mask;
    } else {
        s->regs[R_STATUS] &= ~mask;
    }
}

static void ot_otp_dj_pwr_load_hw_cfg(OtOTPEngineState *s)
{
    OtOTPStorage *otp = s->otp;
    OtOTPHWCfg *hw_cfg = s->hw_cfg;

    memcpy(hw_cfg->device_id, &otp->data[R_HW_CFG0_DEVICE_ID],
           sizeof(hw_cfg->device_id));
    memcpy(hw_cfg->manuf_state, &otp->data[R_HW_CFG0_MANUF_STATE],
           sizeof(hw_cfg->manuf_state));
    memcpy(hw_cfg->soc_dbg_state, &otp->data[R_HW_CFG1_SOC_DBG_STATE],
           sizeof(hw_cfg->soc_dbg_state));
    /* do not prevent execution from SRAM if no OTP configuration is loaded */
    hw_cfg->en_sram_ifetch_mb8 =
        s->blk ? (uint8_t)otp->data[R_HW_CFG1_EN_SRAM_IFETCH] :
                 OT_MULTIBITBOOL8_TRUE;
    /* do not prevent CSRNG app reads if no OTP configuration is loaded */
    hw_cfg->en_csrng_sw_app_read_mb8 =
        s->blk ? (uint8_t)otp->data[R_HW_CFG1_EN_CSRNG_SW_APP_READ] :
                 OT_MULTIBITBOOL8_TRUE;
}

static void ot_otp_dj_pwr_load_tokens(OtOTPEngineState *s)
{
    memset(s->tokens, 0, sizeof(*s->tokens));

    OtOTPTokens *tokens = s->tokens;

    static_assert(sizeof(OtOTPTokenValue) == 16u, "Invalid token size");

    for (unsigned tkx = 0; tkx < OTP_TOKEN_COUNT; tkx++) {
        unsigned partition;
        uint32_t secret_addr;

        switch (tkx) {
        case OTP_TOKEN_TEST_UNLOCK:
            partition = (unsigned)OTP_PART_SECRET0;
            secret_addr = A_SECRET0_TEST_UNLOCK_TOKEN;
            break;
        case OTP_TOKEN_TEST_EXIT:
            partition = (unsigned)OTP_PART_SECRET0;
            secret_addr = A_SECRET0_TEST_EXIT_TOKEN;
            break;
        case OTP_TOKEN_RMA:
            partition = (unsigned)OTP_PART_SECRET2;
            secret_addr = A_SECRET2_RMA_TOKEN;
            break;
        default:
            g_assert_not_reached();
            break;
        }

        OtOTPPartController *pctrl = &s->part_ctrls[partition];
        g_assert(pctrl->buffer.data != NULL);

        /* byte offset of the secret within the partition */
        unsigned secret_offset =
            secret_addr - ot_otp_engine_part_data_offset(s, partition);
        g_assert(secret_offset + sizeof(OtOTPTokenValue) <=
                 OT_OTP_PART_DESCS[partition].size);

        OtOTPTokenValue value;
        memcpy(&value, &pctrl->buffer.data[secret_offset / sizeof(uint32_t)],
               sizeof(OtOTPTokenValue));

        if (s->part_ctrls[partition].locked) {
            tokens->values[tkx] = value;
            tokens->valid_bm |= 1u << tkx;
        }
        trace_ot_otp_load_token(s->ot_id, OTP_TOKEN_NAME(tkx), tkx, value.hi,
                                value.lo,
                                (s->tokens->valid_bm & (1u << tkx)) ? "" :
                                                                      "in");
    }
}

static void ot_otp_dj_signal_pwr_sequence(OtOTPImplIf *dev)
{
    OtOTPEngineState *s = OT_OTP_ENGINE(dev);

    ot_otp_dj_pwr_load_hw_cfg(s);
    ot_otp_dj_pwr_load_tokens(s);
}

static const MemoryRegionOps ot_otp_dj_reg_ops = {
    .read = &ot_otp_dj_reg_read,
    .write = &ot_otp_dj_reg_write,
    .endianness = DEVICE_NATIVE_ENDIAN,
    .impl.min_access_size = 4,
    .impl.max_access_size = 4,
};

static const MemoryRegionOps ot_otp_dj_swcfg_ops = {
    .read_with_attrs = &ot_otp_dj_swcfg_read_with_attrs,
    .endianness = DEVICE_NATIVE_ENDIAN,
    .impl.min_access_size = 4,
    .impl.max_access_size = 4,
};

static void ot_otp_dj_reset_enter(Object *obj, ResetType type)
{
    OtOTPEngineState *s = OT_OTP_ENGINE(obj);
    OtOTPDjClass *dc = OT_OTP_DJ_GET_CLASS(obj);

    memset(s->regs, 0, REGS_SIZE);
    s->regs[R_DIRECT_ACCESS_REGWEN] = 0x00000001u;
    s->regs[R_CHECK_TRIGGER_REGWEN] = 0x00000001u;
    s->regs[R_CHECK_REGWEN] = 0x00000001u;
    s->regs[R_VENDOR_TEST_READ_LOCK] = 0x00000001u;
    s->regs[R_CREATOR_SW_CFG_READ_LOCK] = 0x00000001u;
    s->regs[R_OWNER_SW_CFG_READ_LOCK] = 0x00000001u;
    s->regs[R_OWNERSHIP_SLOT_STATE_READ_LOCK] = 0x00000001u;
    s->regs[R_ROT_CREATOR_AUTH_READ_LOCK] = 0x00000001u;
    s->regs[R_ROT_OWNER_AUTH_SLOT0_READ_LOCK] = 0x00000001u;
    s->regs[R_ROT_OWNER_AUTH_SLOT1_READ_LOCK] = 0x00000001u;
    s->regs[R_PLAT_INTEG_AUTH_SLOT0_READ_LOCK] = 0x00000001u;
    s->regs[R_PLAT_INTEG_AUTH_SLOT1_READ_LOCK] = 0x00000001u;
    s->regs[R_PLAT_OWNER_AUTH_SLOT0_READ_LOCK] = 0x00000001u;
    s->regs[R_PLAT_OWNER_AUTH_SLOT1_READ_LOCK] = 0x00000001u;
    s->regs[R_PLAT_OWNER_AUTH_SLOT2_READ_LOCK] = 0x00000001u;
    s->regs[R_PLAT_OWNER_AUTH_SLOT3_READ_LOCK] = 0x00000001u;
    s->regs[R_EXT_NVM_READ_LOCK] = 0x00000001u;
    s->regs[R_ROM_PATCH_READ_LOCK] = 0x00000001u;

    if (dc->parent_phases.enter) {
        /* OtOTPEngineState cleanup */
        dc->parent_phases.enter(obj, type);
    }
}

static void ot_otp_dj_init(Object *obj)
{
    OtOTPDjState *s = OT_OTP_DJ(obj);
    OtOTPEngineState *es = OT_OTP_ENGINE(obj);

    /* note: device realization is implemented in OtOTPEngineState */

    es->regs = g_new0(uint32_t, REGS_COUNT);
    es->reg_offset.dai_base = R_DIRECT_ACCESS_REGWEN;
    es->reg_offset.err_code_base = R_ERR_CODE_0;
    es->reg_offset.read_lock_base = R_VENDOR_TEST_READ_LOCK;

    /*
     * "ctrl" region covers two sub-regions:
     *   - "regs", registers:
     *     offset 0, size REGS_SIZE
     *   - "swcfg", software config window
     *     offset SW_CFG_WINDOW_OFFSET, size SW_CFG_WINDOW_SIZE
     */
    memory_region_init(&s->mmio.ctrl, obj, TYPE_OT_OTP_DJ "-ctrl",
                       SW_CFG_WINDOW_OFFSET + SW_CFG_WINDOW_SIZE);
    sysbus_init_mmio(SYS_BUS_DEVICE(s), &s->mmio.ctrl);

    memory_region_init_io(&s->mmio.sub.regs, obj, &ot_otp_dj_reg_ops, s,
                          TYPE_OT_OTP_DJ "-regs", REGS_SIZE);
    memory_region_add_subregion(&s->mmio.ctrl, 0u, &s->mmio.sub.regs);

    /* @todo it might be worthwhile to use a ROM-kind here */
    memory_region_init_io(&s->mmio.sub.swcfg, obj, &ot_otp_dj_swcfg_ops, s,
                          TYPE_OT_OTP_DJ "-swcfg", SW_CFG_WINDOW_SIZE);
    memory_region_add_subregion(&s->mmio.ctrl, SW_CFG_WINDOW_OFFSET,
                                &s->mmio.sub.swcfg);
}

static void ot_otp_dj_class_init(ObjectClass *klass, void *data)
{
    (void)data;

    ResettableClass *rc = RESETTABLE_CLASS(klass);
    OtOTPDjClass *dc = OT_OTP_DJ_CLASS(klass);
    resettable_class_set_parent_phases(rc, &ot_otp_dj_reset_enter, NULL, NULL,
                                       &dc->parent_phases);

    OtOTPEngineClass *ec = OT_OTP_ENGINE_CLASS(klass);
    OtOTPIfClass *oc = OT_OTP_IF_CLASS(klass);
    oc->get_lc_info = &ot_otp_dj_get_lc_info;
    oc->get_hw_cfg = ec->get_hw_cfg;
    oc->get_otp_key = ec->get_otp_key;
    oc->get_keymgr_secret = &ot_otp_dj_get_keymgr_secret;
    oc->program_req = ec->program_req;

    OtOTPImplIfClass *ic = OT_OTP_IMPL_IF_CLASS(klass);
    ic->signal_pwr_sequence = &ot_otp_dj_signal_pwr_sequence;
    ic->update_status_error = &ot_otp_dj_update_status_error;

    ic->part_descs = OT_OTP_PART_DESCS;
    ic->part_count = (unsigned)OTP_PART_COUNT;
    ic->part_lc_num = (unsigned)OTP_PART_LIFE_CYCLE;
    ic->sram_key_req_slot_count = NUM_SRAM_KEY_REQ_SLOTS;

    ic->key_seeds = OT_OTP_KEY_SEEDS;
    ic->has_flash_support = false;
    ic->has_zer_support = true;

    g_assert(OT_OTP_KEY_SEEDS[OTP_KEY_SRAM].size ==
             SECRET1_SRAM_DATA_KEY_SEED_SIZE);
}

static const TypeInfo ot_otp_dj_info = {
    .name = TYPE_OT_OTP_DJ,
    .parent = TYPE_OT_OTP_ENGINE,
    .instance_size = sizeof(OtOTPDjState),
    .instance_init = &ot_otp_dj_init,
    .class_size = sizeof(OtOTPDjClass),
    .class_init = &ot_otp_dj_class_init,
    .interfaces =
        (InterfaceInfo[]){
            { TYPE_OT_OTP_IF }, /* public OTP API */
            { TYPE_OT_OTP_IMPL_IF }, /* private OTP API for OTP engine */
            {},
        },
};

static void ot_otp_dj_register_types(void)
{
    type_register_static(&ot_otp_dj_info);
}

type_init(ot_otp_dj_register_types);
