/*
 * Generated from otp_ctrl_mmap.hjson with otptool.py
 * Top version: 5fe6fe8605
 */

/* this prevents linters from checking this file without its parent file */
#ifdef OT_OTP_DJ_PARTS

/* clang-format off */
/* NOLINTBEGIN */
static const OtOTPPartDesc OtOTPPartDescs[] = {
    [OTP_PART_VENDOR_TEST] = {
        .size = 64u,
        .offset = 0u,
        .zer_offset = UINT16_MAX,
        .digest_offset = 56u,
        .hw_digest = false,
        .sw_digest = true,
        .secret = false,
        .buffered = false,
        .write_lock = false,
        .read_lock_csr = true,
        .read_lock = true,
        .integrity = false,
        .zeroizable = false,
    },
    [OTP_PART_CREATOR_SW_CFG] = {
        .size = 304u,
        .offset = 64u,
        .zer_offset = UINT16_MAX,
        .digest_offset = 360u,
        .hw_digest = false,
        .sw_digest = true,
        .secret = false,
        .buffered = false,
        .write_lock = false,
        .read_lock_csr = true,
        .read_lock = true,
        .integrity = true,
        .zeroizable = false,
    },
    [OTP_PART_OWNER_SW_CFG] = {
        .size = 600u,
        .offset = 368u,
        .zer_offset = UINT16_MAX,
        .digest_offset = 960u,
        .hw_digest = false,
        .sw_digest = true,
        .secret = false,
        .buffered = false,
        .write_lock = false,
        .read_lock_csr = true,
        .read_lock = true,
        .integrity = true,
        .zeroizable = false,
    },
    [OTP_PART_OWNERSHIP_SLOT_STATE] = {
        .size = 48u,
        .offset = 968u,
        .zer_offset = UINT16_MAX,
        .digest_offset = UINT16_MAX,
        .hw_digest = false,
        .sw_digest = false,
        .secret = false,
        .buffered = false,
        .write_lock = false,
        .read_lock_csr = true,
        .read_lock = true,
        .integrity = true,
        .zeroizable = false,
    },
    [OTP_PART_ROT_CREATOR_AUTH] = {
        .size = 1424u,
        .offset = 1016u,
        .zer_offset = UINT16_MAX,
        .digest_offset = 2432u,
        .hw_digest = false,
        .sw_digest = true,
        .secret = false,
        .buffered = false,
        .write_lock = false,
        .read_lock_csr = true,
        .read_lock = true,
        .integrity = true,
        .zeroizable = false,
    },
    [OTP_PART_ROT_OWNER_AUTH_SLOT0] = {
        .size = 328u,
        .offset = 2440u,
        .zer_offset = UINT16_MAX,
        .digest_offset = 2760u,
        .hw_digest = false,
        .sw_digest = true,
        .secret = false,
        .buffered = false,
        .write_lock = false,
        .read_lock_csr = true,
        .read_lock = true,
        .integrity = true,
        .zeroizable = false,
    },
    [OTP_PART_ROT_OWNER_AUTH_SLOT1] = {
        .size = 328u,
        .offset = 2768u,
        .zer_offset = UINT16_MAX,
        .digest_offset = 3088u,
        .hw_digest = false,
        .sw_digest = true,
        .secret = false,
        .buffered = false,
        .write_lock = false,
        .read_lock_csr = true,
        .read_lock = true,
        .integrity = true,
        .zeroizable = false,
    },
    [OTP_PART_PLAT_INTEG_AUTH_SLOT0] = {
        .size = 328u,
        .offset = 3096u,
        .zer_offset = UINT16_MAX,
        .digest_offset = 3416u,
        .hw_digest = false,
        .sw_digest = true,
        .secret = false,
        .buffered = false,
        .write_lock = false,
        .read_lock_csr = true,
        .read_lock = true,
        .integrity = true,
        .zeroizable = false,
    },
    [OTP_PART_PLAT_INTEG_AUTH_SLOT1] = {
        .size = 328u,
        .offset = 3424u,
        .zer_offset = UINT16_MAX,
        .digest_offset = 3744u,
        .hw_digest = false,
        .sw_digest = true,
        .secret = false,
        .buffered = false,
        .write_lock = false,
        .read_lock_csr = true,
        .read_lock = true,
        .integrity = true,
        .zeroizable = false,
    },
    [OTP_PART_PLAT_OWNER_AUTH_SLOT0] = {
        .size = 328u,
        .offset = 3752u,
        .zer_offset = UINT16_MAX,
        .digest_offset = 4072u,
        .hw_digest = false,
        .sw_digest = true,
        .secret = false,
        .buffered = false,
        .write_lock = false,
        .read_lock_csr = true,
        .read_lock = true,
        .integrity = true,
        .zeroizable = false,
    },
    [OTP_PART_PLAT_OWNER_AUTH_SLOT1] = {
        .size = 328u,
        .offset = 4080u,
        .zer_offset = UINT16_MAX,
        .digest_offset = 4400u,
        .hw_digest = false,
        .sw_digest = true,
        .secret = false,
        .buffered = false,
        .write_lock = false,
        .read_lock_csr = true,
        .read_lock = true,
        .integrity = true,
        .zeroizable = false,
    },
    [OTP_PART_PLAT_OWNER_AUTH_SLOT2] = {
        .size = 328u,
        .offset = 4408u,
        .zer_offset = UINT16_MAX,
        .digest_offset = 4728u,
        .hw_digest = false,
        .sw_digest = true,
        .secret = false,
        .buffered = false,
        .write_lock = false,
        .read_lock_csr = true,
        .read_lock = true,
        .integrity = true,
        .zeroizable = false,
    },
    [OTP_PART_PLAT_OWNER_AUTH_SLOT3] = {
        .size = 328u,
        .offset = 4736u,
        .zer_offset = UINT16_MAX,
        .digest_offset = 5056u,
        .hw_digest = false,
        .sw_digest = true,
        .secret = false,
        .buffered = false,
        .write_lock = false,
        .read_lock_csr = true,
        .read_lock = true,
        .integrity = true,
        .zeroizable = false,
    },
    [OTP_PART_EXT_NVM] = {
        .size = 1024u,
        .offset = 5064u,
        .zer_offset = UINT16_MAX,
        .digest_offset = UINT16_MAX,
        .hw_digest = false,
        .sw_digest = false,
        .secret = false,
        .buffered = false,
        .write_lock = false,
        .read_lock_csr = true,
        .read_lock = true,
        .integrity = false,
        .zeroizable = false,
    },
    [OTP_PART_ROM_PATCH] = {
        .size = 9864u,
        .offset = 6088u,
        .zer_offset = UINT16_MAX,
        .digest_offset = 15944u,
        .hw_digest = false,
        .sw_digest = true,
        .secret = false,
        .buffered = false,
        .write_lock = false,
        .read_lock_csr = true,
        .read_lock = true,
        .integrity = true,
        .zeroizable = false,
    },
    [OTP_PART_HW_CFG0] = {
        .size = 72u,
        .offset = 15952u,
        .zer_offset = UINT16_MAX,
        .digest_offset = 16016u,
        .hw_digest = true,
        .sw_digest = false,
        .secret = false,
        .buffered = true,
        .write_lock = false,
        .read_lock = false,
        .integrity = true,
        .zeroizable = false,
    },
    [OTP_PART_HW_CFG1] = {
        .size = 16u,
        .offset = 16024u,
        .zer_offset = UINT16_MAX,
        .digest_offset = 16032u,
        .hw_digest = true,
        .sw_digest = false,
        .secret = false,
        .buffered = true,
        .write_lock = false,
        .read_lock = false,
        .integrity = true,
        .zeroizable = false,
    },
    [OTP_PART_SECRET0] = {
        .size = 48u,
        .offset = 16040u,
        .zer_offset = 16080u,
        .digest_offset = 16072u,
        .hw_digest = true,
        .sw_digest = false,
        .secret = true,
        .buffered = true,
        .write_lock = false,
        .read_lock = true,
        .integrity = true,
        .zeroizable = true,
    },
    [OTP_PART_SECRET1] = {
        .size = 32u,
        .offset = 16088u,
        .zer_offset = 16112u,
        .digest_offset = 16104u,
        .hw_digest = true,
        .sw_digest = false,
        .secret = true,
        .buffered = true,
        .write_lock = false,
        .read_lock = true,
        .integrity = true,
        .zeroizable = true,
    },
    [OTP_PART_SECRET2] = {
        .size = 128u,
        .offset = 16120u,
        .zer_offset = 16240u,
        .digest_offset = 16232u,
        .hw_digest = true,
        .sw_digest = false,
        .secret = true,
        .buffered = true,
        .write_lock = false,
        .read_lock = true,
        .integrity = true,
        .zeroizable = true,
        .iskeymgr_creator = true,
    },
    [OTP_PART_SECRET3] = {
        .size = 48u,
        .offset = 16248u,
        .zer_offset = 16288u,
        .digest_offset = 16280u,
        .hw_digest = true,
        .sw_digest = false,
        .secret = true,
        .buffered = true,
        .write_lock = false,
        .read_lock = true,
        .integrity = true,
        .zeroizable = true,
        .iskeymgr_owner = true,
    },
    [OTP_PART_LIFE_CYCLE] = {
        .size = 88u,
        .offset = 16296u,
        .zer_offset = UINT16_MAX,
        .digest_offset = UINT16_MAX,
        .hw_digest = false,
        .sw_digest = false,
        .secret = false,
        .buffered = true,
        .write_lock = false,
        .read_lock = false,
        .integrity = true,
    },
};

#define OTP_PART_COUNT ARRAY_SIZE(OtOTPPartDescs)

/* NOLINTEND */
/* clang-format on */

#endif /* OT_OTP_DJ_PARTS */
