smoke-tests-ot:
  tags:
    - qemu_ot
  stage: test
  needs: ["build-clang"]
  script:
    - build/qemu-system-riscv32 -M help | grep ibexdemo
    - build/qemu-system-riscv32 -M help | grep ot-earlgrey
    - build/qemu-system-riscv32 -M help | grep ot-darjeeling
    - timeout -s KILL 4 build/qemu-system-riscv32 -M ibexdemo -nographic
        -device loader,addr=0x100080,file=build/exit_id.bin -d in_asm,int
    - timeout -s KILL 4 build/qemu-system-riscv32 -M ot-earlgrey,no_epmp_cfg=true -nographic
        -object ot-rom-img,id=rom,file=build/exit_eg.bin,digest=fake,addr=0x8080 -d in_asm,int
    - timeout -s KILL 4 build/qemu-system-riscv32 -M ot-darjeeling,no_epmp_cfg=true -nographic
        -global ot-ibex_wrapper-dj.lc-ignore=on
        -object ot-rom-img,id=rom0,file=build/exit_dj.bin,digest=fake,addr=0x8080 -d in_asm,int
