variables:
  BAREMETAL_REF: "ot-251125-1"
  QEMU_BUILD_OPTS: "--disable-install-blobs"

include:
  - local: '/.gitlab-ci.d/opentitan/build.yml'
  - local: '/.gitlab-ci.d/opentitan/python-ot.yml'
  - local: '/.gitlab-ci.d/opentitan/ot-smoke.yml'
  - local: '/.gitlab-ci.d/opentitan/ot-bmtests.yml'
